### ISSUE TITLE
Unable to visualize QBoxlayout nor QTable 

### ISSUE THREAD

**Issue by jesusdpa1** [napari/magicgui#12]
Hi!

I have been testing the new version of napari and magicgui and was able to get the button example working.

On the other hand when I tried to include additional qt widgets, I notice that this ones where not showing on the napari window. When I remove the @magicgui, and call the functions directly this problem was solved, but I am unable to adjust properly the window specs of, for example, the QBoxLayout.  

Cloud you provide some guidance on how to improve this code?

![image](https://user-images.githubusercontent.com/17010046/81608266-fce46400-93a3-11ea-859c-e253939aa5f5.png)

```python
import os
os.environ["DLClight"]="True"
import napari
import math
from enum import Enum
from magicgui import magicgui
import deeplabcut as dlc
from skimage import data
from magicgui import register_type
from qtpy.QtWidgets import (QTableWidget, QWidget, QBoxLayout, QPushButton,
                            QTableWidgetItem, QLabel, QLineEdit)
from qtpy import QtCore

with napari.gui_qt():
    viewer = napari.view_image(data.astronaut(), rgb=True)

    table_roi = QTableWidget()
    table_roi.setFixedWidth(300)
    table_roi.setColumnCount(1)
    table_roi.setRowCount(15)
    table_roi.setItem(0, 0, QTableWidgetItem(cfg['Task']))
    table_roi.setItem(0, 1, QTableWidgetItem("Cell (1,2)"))
    table_roi.setItem(1, 0, QTableWidgetItem("Cell (2,1)"))
    table_roi.setItem(1, 1, QTableWidgetItem("Cell (2,2)"))

    viewer.window.add_dock_widget(table_roi, area='bottom')

    @magicgui(label_selection={'widget_type': QBoxLayout})
    def label_selection():
        lbl1 = QLabel()
        lbl1.move(15, 1)
        lbl1.setText('test')
        box1 = QLineEdit()
        box1.move(1, 2)

    label_gui = label_selection.Gui(show=True)

    viewer.window.add_dock_widget(label_gui, area='right')
```

**Comment by tlambert03** [comment]
Hi @jesusdpa1, thanks for giving it a try!  Definitely a work in progress, so your feedback is greatly appreciated.

I think there's a bit of a misunderstanding here about what magicgui is going for you and how to use.  I'll explain here, but if there were things in the documentation that you feel led you astray, feel free to point them out so I can think about how to improve them.

There are 2 broader points I would make here:
1. `magicgui` is _mostly_ designed to let you _avoid_ using Qt altogether.  So anytime you find yourself using a Qt widget for something simple like a QLabel or QLineEdit, it should raise a bit of a "is this really necessary?" flag.  The two places where you may need to import actual Qt components are:
    - when you are using the `widget_type` option to override the default widget that `magicgui` uses to represent a certain type.  But not in that case, that the parameter name in your `@magicgui` decorator should match the name a _function parameter_, not the function name itself.  See for example, the `sigma` parameter in [this example](https://magicgui.readthedocs.io/en/latest/examples/napari_parameter_sweep/), where I swapped the widget for a slider instead of a spinbox (the default)
    - advanced usage when you are using [`register_type`](https://magicgui.readthedocs.io/en/latest/type_inference/#register_type) with the `widget_type` options.
2. `magicgui` does not inspect the _body_ of your function, it inspects the _signature_..  So the `lbl1` and `box1` lines in your function are completely invisible to magicgui.  You should use the body of the function to declare what you want to _do_ with the parameters once the user has entered them... not how you want them to be laid out.

So I think what you're going for is this:
```python
@magicgui
def label_selection(box: str, lbl1='test'):
    # whatever you intended to do with the input to "box"
    ...

viewer.window.add_dock_widget(label_selection.Gui(), area='right')
```
I'll note that "labels" are particularly confusing at the moment, and are being added in another [branch](https://github.com/napari/magicgui/tree/labels-forms) ... (see also #13).  So really, if you're just trying to get a widget with a single LineEdit selection to get some text from a user, once that branch merges you should let magicgui make a label for you, and then it would just be:

```python
@magicgui
def your_function(your_label: str):
    ...

viewer.window.add_dock_widget(your_function.Gui(), area='right')
```

currently, it's not possible to do detailed layout modifications like you're trying to do with the `QBoxLayout`, for now it's mostly just a verticalBox or horizontalBox (formLayout coming).

**Comment by jesusdpa1** [comment]
Hi Talley! Thank you very much for the explanation, it was really useful to guide me to develop the gui's I am trying to work on. I saw that most of the errors where lack of knowledge but here are some examples of things I have been working on:

Flowdec
![total](https://user-images.githubusercontent.com/17010046/82256967-3d545c80-9925-11ea-9655-97015e1564bb.png)

DeeplabCut
to visualized and modify the config_file
![image](https://user-images.githubusercontent.com/17010046/82257145-899f9c80-9925-11ea-8321-8226186f00d4.png)

and to add the points to each image

![image](https://user-images.githubusercontent.com/17010046/82257301-ccfa0b00-9925-11ea-9f56-467d8eaef82a.png)

With this implementation, I was wondering if there is a way to block the number of points you can add through the add_points() function. DLC requires the x,y of each individual point attached to their respective labels. I was able to create this viewer (image above) but I am lacking of the capability to limit that number of points to one.

**Comment by tlambert03** [comment]
those look great @jesusdpa1!  (just so I understand though... those are not with magicgui I assume, right? ... if so, would be curious to see the source if you have a link).

>  I was wondering if there is a way to block the number of points you can add through the add_points() function

do you mean in the napari points interface?  or something about magicgui?  If napari, then no... there's currently no way to cap the number of points... but you could hook up a callback to the `Layer.events.data()` event... and disable the add button according to data length?

**Comment by jesusdpa1** [comment]
Thanks!! and you guessed correctly hehe, I had to created the classes with PyQT5. Here is the current code I have to extract the data point from each image. Could you explain more on how to used the callbacks? From what I understand the callbacks for the events.data() are the following:

viewer.layers[1].events.data.callbacks
Out[87]: 
((<weakref at 0x7fe15dbd3590; to 'Viewer' at 0x7fe161550e90>,
  '_on_layers_change'),
 <function napari.layers.base.base.Layer.__init__.<locals>.<lambda>(e)>,
 (<weakref at 0x7fe15dbd6e30; to 'Points' at 0x7fe15c6a0e50>, 'on_data'))

how do I attached this to a function that executes when data is larger than 1

import os
import napari
import math
from enum import Enum
from magicgui import magicgui
import deeplabcut as dlc
# dropdown boxes are best made by creating an enum
from skimage import data
from magicgui import register_type
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import pyqtSlot
from PyQt5.QtCore import QAbstractTableModel, Qt
import dask.array as da
import dask
import imageio
import glob
import pandas as pd
import numpy as np
import itertools

os.environ["DLClight"] = "True"
"""
pip install napari
pip install magicgui
pip install PyQt5

"""


class load_images(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):

        self.boxview = QtWidgets.QGroupBox()
        self.layout = QtWidgets.QGridLayout()
        self.btn_load = QtWidgets.QPushButton('Load Images')
        self.layout.addWidget(self.btn_load, 0, 0)
        self.setLayout(self.layout)
        self.btn_load.clicked.connect(self.btnstate)

    @QtCore.pyqtSlot()
    def btnstate(self):
        path_to_folders = glob.glob(os.path.join(cfg['project_path'], 'labeled-data', '*[!labeled]'))
        path_to_images = []
        for files_n in range(len(path_to_folders)):
            img_paths = glob.glob(os.path.join(path_to_folders[files_n], '*.png'))
            path_to_images = path_to_images + img_paths

        sample = imageio.imread(path_to_images[0])
        lazy_arrays = [dask.delayed(imageio.imread)(fn) for fn in path_to_images]
        lazy_arrays = [da.from_delayed(x, shape=sample.shape, dtype=sample.dtype)
                       for x in lazy_arrays]

        viewer.add_image(da.stack(lazy_arrays), name='to_label')
        viewer.window.add_dock_widget(label_img(), area='right', name='label images')


class pandasModel(QAbstractTableModel):

    def __init__(self, data):
        QAbstractTableModel.__init__(self)
        self._data = data

    def rowCount(self, parent=None):
        return self._data.shape[0]

    def columnCount(self, parnet=None):
        return self._data.shape[1]

    def data(self, index, role=Qt.DisplayRole):
        if index.isValid():
            if role == Qt.DisplayRole:
                return str(self._data.iloc[index.row(), index.column()])
        return None

    def headerData(self, col, orientation, role):
        if orientation == Qt.Horizontal and role == Qt.DisplayRole:
            return self._data.columns[col]
        return None

class get_points(QtWidgets.QWidget):
    def __init__(self):
        """Constructor"""
        super(get_points, self).__init__()
        self.labels = cfg['bodyparts']
        self.layout = QtWidgets.QGridLayout()
        # Add toolbar and items
        self.boxview = QtWidgets.QGroupBox()
        self.btn_save = QtWidgets.QPushButton('Update Data Points')

        self.layout.addWidget(self.btn_save, 0, 0)
        self.setLayout(self.layout)
        self.btn_save.clicked.connect(self.btnstate)

        labels = cfg['bodyparts']
        total_lbl = np.repeat(list(labels), 2)
        axis_list = np.array(['_x', '_y'] * int(len(total_lbl) / 2))
        final_lbl = (pd.Series(total_lbl) + axis_list).tolist()
        self.df_lbl = pd.DataFrame(columns=final_lbl)


    def create_pandas(self):
        for lbl_n in range(len(self.labels)):
            if viewer.layers[labels[lbl_n]] in viewer.layers:
                point_data = viewer.layers[labels[lbl_n]].data
                if point_data.size > 0:
                    print(point_data)

    @QtCore.pyqtSlot()
    def btnstate(self):
        self.df_lbl.loc[len(self.df_lbl)] = 0
        for n in range(len(viewer.layers)):
            if isinstance(viewer.layers[n], napari.layers.points.points.Points):
                layer_name = viewer.layers[n]._name
                if viewer.layers[layer_name] in viewer.layers:
                    point_data = viewer.layers[layer_name].data
                    if point_data.size > 0:
                        # self.df_lbl['_'.join([layer_name, 'x'])] = point_data[0][0]
                        # self.df_lbl['_'.join([layer_name, 'y'])] = point_data[0][1]
                        print(point_data)


class label_img(QtWidgets.QWidget):

    def __init__(self):
        """Constructor"""
        super(label_img, self).__init__()

        layout = QtWidgets.QVBoxLayout()

        labels = cfg['bodyparts']
        for label in labels:
            btn = QtWidgets.QCheckBox(label)
            btn.stateChanged.connect(self.clicked)
            layout.addWidget(btn)
        self.setLayout(layout)

    # ----------------------------------------------------------------------
    def clicked(self):
        """
        Change label based on what button was pressed
        """
        button = self.sender()
        if button.isChecked():
            print(button.text() + " is selected")
            viewer.add_points(name=button.text())

        elif not button.isChecked():
            print(button.text() + " is deselected")
            viewer.layers.remove(button.text())

    def diseable_point(self):

        for n in range(len(viewer.layers)):
            layer_name = viewer.layers[n]._name
            print(layer_name)
            if layer_name in cfg['bodyparts']:
                if viewer.layers[layer_name].data > 0:
                    viewer.layers[layer_name].events.block_all()

cfg = dlc.auxiliaryfunctions.read_config('/media/jesusdpa/Work_HubMap/Optogenetics/update_Krause_Opto-JDPA-2019-12-06/config.yaml')

#%% Almost
with napari.gui_qt():
    viewer = napari.view_image(data.astronaut(), rgb=True)
    labels = cfg['bodyparts']

    if viewer.layers.events.emitters['added'] == True:
        print(True)
    viewer.window.add_dock_widget(load_images(), area='left', name='load images')
    viewer.window.add_dock_widget(get_points(), area='left', name='get points')

![image](https://user-images.githubusercontent.com/17010046/82385424-1454ca00-9a00-11ea-854f-ab44ab71947a.png)

**Comment by tlambert03** [comment]
> how do I attached this to a function that executes when data is larger than 1

(assuming `points` is the name of a napari `Points` layer)

```python
points = viewer.add_points(...)

def handle_data_change(event):
    # the event has a `source` attribute that is the layer
    points_layer = event.source
    if len(points_layer.data) > 0:
        # whatever you want
        ...

points.events.data.connect(handle_data_change)      
```



but I actually have another question:  _why_?  😅
It looks from your example that you might want to limit it to one point per layer, because you want to associate some metadata with each point, and you're using the layer name to do so?
Just want to make sure that you're aware that you can associate arbitrary properties/metadata with each point.  (See the [add_points_with_properties example](https://github.com/napari/napari/blob/master/examples/add_points_with_properties.py))

**Comment by tlambert03** [comment]
gonna close this, but feel free to open again if you need help

**Comment by jesusdpa1** [comment]
Sorry about that got distracted and never sent the response. Thanks for the tip, I updated the framework. You where right, there was no need for the extra steps I was taking
