### ISSUE TITLE
make vertical layout default

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#121]
@jni has proposed that we make `layout='vertical'` be default for magicgui widgets.  Curious if anyone has any objections to that?  (you can, of course, still use `layout='horizontal'`.

@HagaiHargil, @haesleinhuepf, @sofroniewn

**Comment by sofroniewn** [comment]
Fine with me! Makes for nicer symmetry with napari default :-)

**Comment by sofroniewn** [comment]
Thinking about #111 a little more, I might also propose that we also add a stretch by default to the bottom of the widget. I personally would find that more visually appealing (we could think about making it a kwarg if people wanted control, but that wouldn't be needed for me). Curious how others feel and if they have a similar personal preference or not

**Comment by HagaiHargil** [comment]
I have no opinion on the stretch thing, but I always use `layout='form'` which is essentially vertical, so I agree that it's a better default.
