### ISSUE TITLE
Adding a stretch to the bottom of widgets

### ISSUE THREAD

**Issue by sofroniewn** [napari/magicgui#127]
Thinking about #111 a little more, I might also propose that we also add a stretch by default to the bottom of the widget. I personally would find that more visually appealing (we could think about making it a kwarg if people wanted control, but that wouldn't be needed for me). Curious how others feel and if they have a similar personal preference or not

_Originally posted by @sofroniewn in https://github.com/napari/magicgui/issues/121#issuecomment-765813271_

**Comment by sofroniewn** [comment]
Just pulled this out into its own issue if people want to discuss more.

**Comment by tlambert03** [comment]
Thanks @sofroniewn,  I think my feeling is probably that napari should be doing this, not magicgui.  the desire seems to come from the way it looks in the dock widget on the right side of napari.  But I'm not sure magicgui should be making that assumption about its layouts

**Comment by sofroniewn** [comment]
That's fair enough - what would it take to make about an API way to specify this that doesn't involve going into `native` or exposing a flag that napari can optionally set if we don't make it a default?

**Comment by tlambert03** [comment]
> what would it take to make about an API way to specify this that doesn't involve going into native or exposing a flag that napari can optionally set if we don't make it a default?

I guess I mean that we should add additional stretch to the dock_widget that contains the provided widget.  And not touch the provided widget itself.

**Comment by sofroniewn** [comment]
ah nice, i hadn't really considered that as an option, that could work really nicely!!

**Comment by sofroniewn** [comment]
ok, i'm happy to close this as there seems to be a nice work around for napari, if anyone else wants this in the future I guess they can reopen!
