### ISSUE TITLE
Automagically add labels per field

### ISSUE THREAD

**Issue by HagaiHargil** [napari/magicgui#13]
I love MagicGUI, thanks for making it! What do you think of automatically adding labels next to each field? In your canonical example from the docs, this means that each field would have a little label with the name of the parameter its referencing (n1, n2, etc), right above or to the left of it.

This could obviously be optional (and off by default), and there can also be some simple heuristic to transform `snake_case` variable names to native-English-looking words.

**Comment by tlambert03** [comment]
Thanks @HagaiHargil!  Yes that’s sorely needed!  There’s a branch on this repo where I started working on it.  I’ll get back on it... won’t be too hard to finish up

**Comment by tlambert03** [comment]
Labels are now added by default as of #14 (use `labels=False` to turn them off) and will be in the next release (which I'll push soon)

**Comment by HagaiHargil** [comment]
Amazing! Thanks.
