### ISSUE TITLE
Add a cache keyword to read parameter values from disk

### ISSUE THREAD

**Issue by HagaiHargil** [napari/magicgui#152]
It could be nice if I could decorate a function with a 'cache' keyword so that when this function is run it will write to disk the last parameter values used to run it. Later, when it's re-run, these values will be read back and override any default keyword arguments that the function might have:

Example:

```python
@magicgui(cache=True, call_button='Run')
def test(a: int, b: int = 0) -> int:
    return a + b
```

On its first run, the values displayed will be 'empty' for `a` and `0` for `b`. If I run it with `a = 2` magicgui will write to the user's cache directory a snippet with `a = 2`, `b = 0`. This snippet will be looked-for and loaded during a consecutive call to `test`, as long as its run as a GUI (and not a standard function).

I tried implementing this behavior as a wrapper class but it became clear that I'll have to redo it for each and every magicgui script I have, and the work itself was quite tedious. If you think that this `cache` keyword fits the overall idea of magicgui I might try doing it myself, but not in the immediate future.

**Comment by tlambert03** [comment]
I can definitely see the benefit of something like this.  Just to make sure I'm understanding, you're talking about caching the _output_ of the function given a parameter set right?

my first thought is that it would be nice not to reinvent any wheels here.  So something like `lru_cache` immediately comes to mind... and it seems to work well right out of the box:
![r](https://user-images.githubusercontent.com/1609449/107879572-a0b8ee00-6ea7-11eb-81b7-e2a11aab3aa8.gif)

of course, that is just in-memory cache... but a modification could allow caching to disk too.

> as long as its run as a GUI (and not a standard function).

What's the significance of that distinction?  Why not cache the result either way

**Comment by tlambert03** [comment]
or, since you specifically said "parameter values" here ... maybe you mean you want the state of the gui to "pre-load" with the last-used user defaults?

**Comment by HagaiHargil** [comment]
I wasn't clear enough, sorry. I definitely meant caching the parameter values that were used in the last run, not the output. 

Pre-loading parameter helps during consecutive runs in terms of UX. I have a couple of GUIs that have a couple of file path inputs and a few hard-to-remember floating point values. Starting the GUI resets the home directory where the file dialog opens and changes these floats to their original values. Since the needed directories are deeply-nested it's quite unergonimic to navigate to approximately the same place every time, but I can't change the default directory since other users need other directories.

**Comment by tlambert03** [comment]
makes sense!  good feature.

**Comment by tlambert03** [comment]
Is this something you'd _like_ to implement when you get the time?  or something that you'd be happy to see done however/whenever, as long as it gets added?

**Comment by HagaiHargil** [comment]
I'll be happy to see it done however. I won't have much spare time in the coming weeks, and this isn't top priority for me, so I can't help ATM.
