### ISSUE TITLE
Applying successives filters / function on the same layer

### ISSUE THREAD

**Issue by bioimage-analysis** [napari/magicgui#16]
## ❓ Questions and Help

First of all, thank you for magicgui,  just started playing with it and it's pretty awesome.  I have a pretty simple question:

If I take the example from the documentation:
```python
@magicgui(
        auto_call=True,
        sigma={"widget_type": QDoubleSlider, "maximum": 6, "fixedWidth": 400},
        mode={"choices": ["reflect", "constant", "nearest", "mirror", "wrap"]},
    )
    def gaussian_blur(layer: Image, sigma: float = 1.0, mode="nearest") -> Image:
        """Apply a gaussian blur to ``layer``."""
        if layer:
            return skimage.filters.gaussian(layer.data, sigma=sigma, mode=mode)
```
But let say I wanted to apply ```skimage.filters.median``` as well to the same layer image while being able to adjust the selem size, what would be the best and cleanest way to go about it? I try few things but ended work on 2 separates layers.

[ ] I have searched the [documentation](https://magicgui.readthedocs.io/)

**Comment by tlambert03** [comment]
Hey @bioimage-analysis,
I'm not sure if this is quite what you mean... but if you _know_ you want to chain a gaussian blur followed by a median filter... this would be one way to do it:
```python
    @magicgui(
        auto_call=True,
        sigma={"widget_type": QDoubleSlider, "maximum": 6, "fixedWidth": 200},
        mode={"choices": ["reflect", "constant", "nearest", "mirror", "wrap"]},
        selem_shape={"choices": ["diamond", "disk", "square"]},
    )
    def gaussian_blur(
        layer: Image,
        sigma: float = 1.0,
        mode="nearest",
        selem_shape="disk",
        selem_size: int = 3,
    ) -> Image:
        """Apply a gaussian blur to ``layer``."""
        if layer:
            blurred = skimage.filters.gaussian(layer.data, sigma=sigma, mode=mode)
            selem = getattr(skimage.morphology.selem, selem_shape)
            return skimage.filters.median(blurred, selem(selem_size))
```

which yields something like:

![Untitled](https://user-images.githubusercontent.com/1609449/82514222-2bb8b380-9ae3-11ea-8180-3c8f43c290cb.gif)

but of course, we're hard coding "gaussian, then median"...  if what you're asking is "how do I chain an arbitrary number of functions together"... then that's a bit harder at the moment (but something like that is in the works).  Is that what you mean?  or did this help?

**Comment by bioimage-analysis** [comment]
Wow, that was fast, thank you! It's exactly what I was trying to do. 
But indeed, ultimately, I would like to chain an arbitrary number of function.
Ideally, what I would like to do, would be:
1 - Background correction
2 - Deconvolution
3 - Extended depth of field
etc...
i - segmentation

Just to have an idea of what work best before running it on all the images. At the moment I am trying to see what is possible.

**Comment by tlambert03** [comment]
That's definitely a use case I'd like to support here!  Ultimately, I'd like these widgets to be composable, and nestable (e.g. using a function as a parameter makes a nested widget).

For what it's worth, I had a project that I was working on for a while that attempts to build that sort of "autogui" from an arbitrary sequence of python functions: [mosaicpy](https://github.com/tlambert03/MOSAICpy), (see the "basic idea" in the readme there). I think it would be possible here to do something similar: make a "list item widget" where the items in the list are (sortable) functions, each of which is rendered as a magicgui, and outputs are chained together...

Thanks for your note! I'll definitely keep this use case in mind and try to work on something soon.

**Comment by bioimage-analysis** [comment]
Thank you, mosaicpy is exactly what I have in mind with the visualization capability of napari. Thanks again for your answers.

**Comment by tlambert03** [comment]
then rest assured we're excited about the same goals! 😄
if you happen to develop any neat approaches or uses of magicgui/napari in the meantime, feel free to let us know and/or submit a PR!

**Comment by bioimage-analysis** [comment]
Hi @tlambert03 , as I am trying to improve my skills at pyqt and understand how magigui work I came into a very simple problem:
When you decorate your `gaussian_blur` with `@magicgui`, if you then change the value of the sigma widget, you only "update" the layer in napari. I try to recreate that using pyqt as follow:
```python
sld = QSlider(Qt.Horizontal, self)
        sld.valueChanged[int].connect(self.updateValue)

    @staticmethod
    def updateValue(value):
        viewer.add_image(filters.gaussian(viewer.active_layer.data, sigma=value))
        viewer.layers.select_previous()
        viewer.layers.remove_selected()
```
But obviously I don't get the same result as I am just replacing the layer and I am not able to go back to the original image. I was wondering what is happening in magicgui that I am missing?

**Comment by tlambert03** [comment]
Ah. more magic :)
If I understand the question correctly, the bit of code you'll want to look at is actually in napari... The reason the image even gets added to the viewer at all is because `napari` has "registered" the `napari.layers.Layer` type with `magicgui` (right [here](https://github.com/napari/napari/blob/master/napari/utils/_magicgui.py#L38)) using the [`register_type` ](https://magicgui.readthedocs.io/en/latest/type_inference/#register_type) function.  `register_type(type, return_callback =callback)` basically tells `magicgui`, "whenever someone annotates their decorated function with a return type of `type` (or a subclass of it), then call my `callback` function with the output of the function.  (looks like i need to update the docs with that `return_callback` bit).
In this case, the callback function that napari has registered is `show_layer_result` right [here](https://github.com/napari/napari/blob/master/napari/utils/_magicgui.py#L78-L140).  so _that's_ the function you should look at to see how to update layer.

it mostly comes down to these lines:
```python
    try:
        # try to find a layer of a given name, and update the data
        viewer.layers['name_of_layer'].data = result
    except KeyError:
        # otherwise add a new image
        viewer.add_image(data=result, name='name_of_layer')
```
did that answer it?  or did i miss the point...

**Comment by bioimage-analysis** [comment]
That was some tricky magic here (at least for me), I didn't think about checking into napari for some magicgui and was getting quite confuse. Anyway, your answer was exactly was I was looking for.

**Comment by tlambert03** [comment]
The core idea here is that magicgui basically just brokers mappings between types and widgets (in the function signature), or return annotations and callbacks.  magicgui doesn't know anything about napari, (it doesn't import napari or depend on napari in any way), but it does allow third party packages to "register" their own custom classes with magicgui so as to provide "sane defaults": for instance, when you annotate a function parameter as a napari Layer `def function(image1: napari.image.Layers):`, then magic gui will render that as a dropdown box with all of the current viewer image layers _because napari has told it to do so_.  Had napari _not_ done that, then magicgui would have do idea what to do with a parameter with type `napari.image.Layers` (unless the user instructed it manually).

If at any point you want to "opt-out" of the behavior that a third party package like `napari` has registered, then you either can _not_ annotate your parameter or return type as that third party class ... in which case you'll need to tell magicgui what to do with that type, by _either_ directly [specifying the `widget_type` argument](https://magicgui.readthedocs.io/en/latest/configuration/#widget_type) (manually passing a QtWidget for magicgui to use), or you can override the third party behavior by [registering your own widget](https://magicgui.readthedocs.io/en/latest/type_inference/#register_type) for the corresponding type:
```python
from magicgui import register_type

register_type(napari.layers.Layer, widget_type=MyCustomQtWidget)

**Comment by tlambert03** [comment]
Hi @bioimage-analysis... I'm going to close this issue.  But don't hesitate to check back in for any help with magicgui.  I'll note that a lot has changed since this was opened, with the release of v0.2.0.  So if you pick up working with magicgui again in the future, check out the [migration guide](https://napari.org/magicgui/api/v0_2_0.html).
cheers!
