### ISSUE TITLE
Better error message on bad keyword argument to `magicgui`

### ISSUE THREAD

**Issue by HagaiHargil** [napari/magicgui#165]
(I'm sorry for the barrage today, I just found a bit of time for cleanup. Also, if the master-only bugs are irrelevant please say so and I'll close these issues immediately)

**Describe the bug**

Adding the `persist` keyword to the decorator returns an immediate error in the current master branch.

**To Reproduce**
```python
from magicgui import magicgui


@magicgui(presist=False)
def a(b: float):
    print("O_O")

a.show(run=True)
```
When run in a fresh environment it returns:
```
Traceback (most recent call last):
  File "/home/hagai/Code/magicgui/../../te.py", line 5, in <module>
    def a(b: float):
  File "/home/hagai/miniconda3/envs/magicgui/lib/python3.9/site-packages/magicgui/_magicgui.py", line 205, in inner_func
    return magic_class(func, **kwargs)
  File "/home/hagai/miniconda3/envs/magicgui/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 138, in __init__
    raise TypeError("'param_options' must be a dict of dicts")
TypeError: 'param_options' must be a dict of dicts
```

**Expected behavior**
No error should be raised.

**Environment (please complete the following information):**
 - OS: Linux
 - backend: pyqt5
 - magicgui version [e.g. 0.1.0]: Latest master

**Comment by tlambert03** [comment]
is this maybe a typo in your parameter (`presist` rather than `persist`), combined with a less-than-helpful error message?

**Comment by tlambert03** [comment]
> sorry for the barrage today

no worries at all, they are greatly appreciated!

**Comment by HagaiHargil** [comment]
Oh noes :scream: 
I made the same typo twice, in two independent cases, before coming here :(

Sorry about that.

**Comment by tlambert03** [comment]
I still think the error message should be clearer.  so I'll re-open this and change the title, until I fix it.  thanks again!
