### ISSUE TITLE
Parameter value persistance causes error with napari layers as parameter types

### ISSUE THREAD

**Issue by adamltyson** [napari/magicgui#169]
**Describe the bug**
Using `@magicgui(persist=True)` works fine in a plugin, except the case when I have something like `image: napari.layers.Image` as an input parameter, e.g.  [here](https://github.com/brainglobe/cellfinder-napari/blob/6938485e38510a5688b3fccdefdf04eb2c322009/cellfinder_napari/cellfinder_napari.py#L31).

If I change the parameters, then re-start napari, the plugin doesn't start and I get an error. 

**To Reproduce**

`napari`
*Load plugin, change a parameter & close napari*
`NAPARI_CATCH_ERRORS=0 napari`
*Try to load plugin*
```
(napari-cellfinder) adam@garfield:~/projects/cellfinder-napari$ NAPARI_CATCH_ERRORS=0 napari
09:58:45 WARNING Could not import pyopencl. Falling back to scipy for CPU affine transforms
09:58:47 ERROR Unhandled exception:
Traceback (most recent call last):
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 450, in _add_widget
    self._add_plugin_dock_widget(key)
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 568, in _add_plugin_dock_widget
    wdg = Widget(**kwargs)
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/magicgui/_magicgui.py", line 200, in __call__
    widget = self.func(param_options=prm_options, **{**self.keywords, **kwargs})
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 199, in __init__
    self._load(quiet=True)
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/magicgui/widgets/_function_gui.py", line 379, in _load
    super()._load(path or self._dump_path, quiet=quiet)
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/magicgui/widgets/_bases/container_widget.py", line 300, in _load
    getattr(self, key).value = val
  File "/home/adam/miniconda3/envs/napari-cellfinder/lib/python3.8/site-packages/magicgui/widgets/_bases/categorical_widget.py", line 38, in value
    raise ValueError(
ValueError: None is not a valid choice. must be in ()
```

This error doesn't occur if I:
* delete the cache file before re-starting napari
* Don't have a napari layer as parameter type in my decorated function

**Expected behavior**
All the parameters to be reloaded whether or not one of the inputs is a napari layer

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - backend: PySide2
 - magicgui version: 0.2.7

P.S. the parameter persistence is really helpful for my plugin, thanks!

**Comment by jni** [comment]
Ha, I totally thought this could happen when I read the release notes (what if the parameter selection isn't valid anymore e.g. because no layers are loaded), and thought, nah, I'm sure @tlambert03 took care of it somehow... :joy:

**Comment by tlambert03** [comment]
Ah thanks @adamltyson.  Indeed I wasn't even really thinking about napari in this feature.  I'll make it fail more gracefully here

**Comment by uschmidt83** [comment]
Furthermore, I noticed that _sometimes_ parameter changes are not persisted because the parameter change doesn't trigger the function to save the value. This happened when I quickly changed the value of a `FloatSpinBox` by clicking the `+` or `-` buttons. I know this is a separate issue, but I wouldn't know how to reproduce it anyway.

**Comment by tlambert03** [comment]
There is a debounce applied to the save-to-disk function so it only runs once every 250ms.  So if changes are applied in rapid succession, it's possible that the last changes will be missed.  This was to prevent something like a slider causing a ton of disk events... I'll try to add logic to make sure that the last event is always registered.

**Comment by Eddymorphling** [comment]
Hi Tally,
I am a new user to napari and have been playing with the sample lattice light sheet dataset you had mentioned in the github page link. I come across the same error - `Could not import pyopencl. Falling back to scipy for CPU affine transforms` every time I play with the 4D stack and becomes very sluggish. Am I doing something wrong?

**Comment by Eddymorphling** [comment]
Strange, its fixes itself after I played around with the dataset a few times. All good now :)
