### ISSUE TITLE
EventEmitter loop in napari dock widget

### ISSUE THREAD

**Issue by uschmidt83** [napari/magicgui#187]
**Describe the bug**

`RuntimeError: EventEmitter loop detected!` occurs, although events should be blocked (as far as I understand).

```python
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/uwe/research/stardist/napari/magicgui/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/home/uwe/research/stardist/napari/magicgui/magicgui/events.py", line 576, in __call__
    raise RuntimeError("EventEmitter loop detected!")
RuntimeError: EventEmitter loop detected!
```

**To Reproduce**

Code for simple napari dock widget (bug is triggered when entering lowercase characters for `param`):

```python
from napari_plugin_engine import napari_hook_implementation
from magicgui import magic_factory

def to_upper(event):
    val = str(event.value)
    if val != val.upper():
        with event.source.changed.blocker():
            event.source.value = val.upper()

def widget_init(widget):
    widget.param.changed.connect(to_upper)

@magic_factory(widget_init=widget_init)
def widget(param: str):
    pass

@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    return widget
```

**Expected behavior**
No `RuntimeError: EventEmitter loop detected!`.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - magicgui version 0.2.7

**Comment by tlambert03** [comment]
can repeat, thanks!   Interestingly, it _doesn't_ happen with `@magicgui` ...  will try to fix soon

**Comment by uschmidt83** [comment]
FYI, it also happens with `@magicgui` and a wrapper function:
```python
def widget_wrapper():
    @magicgui
    def widget(param: str):
        pass
    ...
    return widget

@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    return widget_wrapper
```

**Comment by tlambert03** [comment]
strange, now I can't repeat this... I tried checking out various older versions of magicgui (back to 0.2.7) and napari, and various versions of pyqt5/pyside2 but nothing cause the emitter loop.  Here's the script I was using to test it:

<details>

```python
from napari_plugin_engine import napari_hook_implementation
from magicgui import magic_factory
import napari


def to_upper(event):
    val = str(event.value)
    if val != val.upper():
        with event.source.changed.blocker():
            event.source.value = val.upper()


def widget_init(widget):
    widget.param.changed.connect(to_upper)


@magic_factory(widget_init=widget_init)
def widget(param: str):
    pass


class Plugin:
    @napari_hook_implementation
    def napari_experimental_provide_dock_widget():
        return widget


napari.plugins.plugin_manager.register(Plugin, name="test")
viewer = napari.Viewer()
viewer.window.add_plugin_dock_widget("test")
napari.run()
```

</details>

@uschmidt83, sorry to trouble you with this, but if you have a moment, could you try this out again and give me your full `pip list` and python version?  I didn't test on ubuntu today (but when I tried previously, it had also failed on mac)

**Comment by uschmidt83** [comment]
Hi Talley, I also cannot reproduce the issue when I run it via `python bug.py` and type into the param field. (`bug.py` contains your script verbatim).

However, using IPython via `ipython -i bug.py` triggers the bug with the following output:
```python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

Traceback (most recent call last):
  File "/home/uwe/research/stardist/napari/magicgui/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/home/uwe/research/stardist/napari/magicgui/magicgui/events.py", line 625, in __call__
    raise RuntimeError("EventEmitter loop detected!")
RuntimeError: EventEmitter loop detected!

If you suspect this is an IPython 7.20.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by uschmidt83** [comment]
Strange, the bug happens via both Python and IPython in my plugin.

**Comment by tlambert03** [comment]
perfect, thank you!  I probably also used ipython the last time I tried it and forgot

**Comment by tlambert03** [comment]
> Strange, the bug happens via both Python and IPython in my plugin.

as long as I can reproduce somewhere, I can probably fix it in both
If I remember correctly, it had something to do with the order of connecting events... (though that shouldn't matter).
