### ISSUE TITLE
Duplicate change events for RadioButtons widget

### ISSUE THREAD

**Issue by uschmidt83** [napari/magicgui#188]
**Describe the bug**
Every value change triggers two change events for `RadioButtons`.
(Doesn't seem to apply if no value is set initially.)

**To Reproduce**
```python
>>> from magicgui.widgets import RadioButtons
>>> from datetime import datetime

>>> radio = RadioButtons(choices=['A','B'])
>>> radio.changed.connect(lambda e: print(f"{datetime.now()}: {e.value}"))

>>> radio.value = 'A'
2021-03-20 18:41:54.797662: A

>>> radio.value = 'B'
2021-03-20 18:41:54.797729: B
2021-03-20 18:41:54.797758: B

>>> radio.value = 'A'
2021-03-20 18:41:54.797797: A
2021-03-20 18:41:54.797823: A
```

**Expected behavior**
Only one change event per value change.

**Environment (please complete the following information):**
 - OS: Linux
 - magicgui at commit 260f63ecb135fd49250dc78c683795fdeece0538

**Comment by tlambert03** [comment]
yeah :/ this one is slightly tough... one of the events is for the "unchecking" of the first button, the latter is for the selection of the second one.  This is partly due to the lack of good events on the Qt side to convert.  They are designed with non-exclusive radio buttons in mind, so basically the buttons don't necessarily know about each other (and if we ignored or blocked the "unchecking" event, there is the risk that there would never be any event at all).  I did spend some time trying to find a workaround in #183, but never hit on anything I was satisfied with.  Thanks for opening an issue though...  I'll try to pick it up again in the near future.

**Comment by uschmidt83** [comment]
> one of the events is for the "unchecking" of the first button, the latter is for the selection of the second one (hence why it doesn't apply to the first one where there is no current value).

Yes, that's what I assumed.

> (and if we ignored or blocked the "unchecking" event, there is the risk that there would never be any event at all).

I don't understand how that could happen. Won't there always be an event for the button that gets checked?

**Comment by tlambert03** [comment]
not if it's set programmatically.  which wasn't (yet) an assumption I want to make.  in any case, it's not unsolvable.  it's just slightly tricky to come up with a universal solution regardless of how the value was changed

**Comment by tlambert03** [comment]
this also goes back to the assumption of exclusivity.  Currently, radio groups are exclusive, so I could take advantage of that in the short-term... but i'd like to come up with a solution that doesn't absolutely restrict these to being exclusive (though of course, that's the most common application)

**Comment by uschmidt83** [comment]
I assumed that radio buttons were only meant to be exclusive, everything else I'd call a checkbox. Wikipedia agrees with me [on that](https://en.wikipedia.org/wiki/Radio_button):

> A radio button or option button is a graphical control element that allows the user to choose only one of a predefined set of mutually exclusive options. The singular property of a radio button makes it distinct from a checkbox, which allows more than one (or no) item to be selected and for the unselected state to be restored.

Hence, I was about to make a PR with this simple change:

```diff
diff --git a/magicgui/backends/_qtpy/widgets.py b/magicgui/backends/_qtpy/widgets.py
index 1c8df19..c3d238c 100644
--- a/magicgui/backends/_qtpy/widgets.py
+++ b/magicgui/backends/_qtpy/widgets.py
@@ -553,7 +553,7 @@ class RadioButtons(
 
     def _emit_data(self, btn):
         data = self._mgui_get_value()
-        if data is not None:
+        if data is not None and btn == self._btn_group.checkedButton():
             self._event_filter.valueChanged.emit(data)
 
     def _mgui_bind_change_callback(self, callback):
```

If you don't want to always assume exclusivity for `RadioButtons`, then please give me a way to handle this in my code, e.g. by passing on some sort of identity of the button that created the event, or by telling me if the button that triggered the event is currently checked.

**Comment by tlambert03** [comment]
As mentioned, I get that exclusivity is by far the predominant use case. Most gui backends still allow non exclusive use though and I was hoping at first to be able to maintain that option.  But I'd say your use case is far more important than some far off hope.  I'd happily accept your PR!  We can revisit later if we need

**Comment by uschmidt83** [comment]
> Most gui backends still allow non exclusive use though and I was hoping at first to be able to maintain that option.

Sorry, but I still don't understand. I think the widget name `RadioButtons` implies exclusive use of one of the choices, whereas a different widget for grouped choices, say `CheckBoxes`, would imply non-exclusivity. Internally, those widgets would differ only slightly (by the look of their buttons, and the events they emit).

> But I'd say your use case is far more important than some far off hope.

In my current use case, the change event from `RadioButtons` will trigger a file to be downloaded, which thus happens twice (before the file is cached). I could work around it, but it would be annoying 😉.

> I'd happily accept your PR!

Since it's just one line of code, it's probably easier if you do it yourself. However, I'll make a PR if you want me to.

**Comment by tlambert03** [comment]
i don't think there's any disagreement here!  i'm just trying to give you some background on why i didn't immediately make it that way right off the bat.  I totally agree about the intended meaning of the name `RadioButtons` and  `CheckBoxes`.  The only point I was making is the Qt _allows_ you to have a group of radio buttons that are not exclusive (whether or not that's how wikipedia or anybody else "conceives" of radio buttons, the point is, Qt, makes it _possible_).  In other words, this isn't about semantics... just about extending a backend API.  I 100% understand that double-event emission is worse, and that's why I'm all on board!.

if you'd rather not bother, I'm happy to make the PR.  thanks again!

**Comment by uschmidt83** [comment]
I understand you now. Thanks for the explanation!

> The only point I was making is the Qt _allows_ you to have a group of radio buttons that are not exclusive (whether or not that's how wikipedia or anybody else "conceives" of radio buttons, the point is, Qt, makes it _possible_).

Ok, Qt is weird then 😉

> if you'd rather not bother, I'm happy to make the PR.

I'll only do it if it's actually less work for you.

**Comment by tlambert03** [comment]
> Ok, Qt is weird then 😉

definitely 😂 

I'll take care of it tomorrow.  want to add some tests too so don't mind doing it.

**Comment by jni** [comment]
Arriving late to this, but @tlambert03 I'm going to have to agree with @uschmidt83's general gist here which is that even if *Qt* allows non-exclusive radiobuttons, magicgui can take the liberty of ignoring that and forcing exclusivity. I don't believe we are aiming for 100% coverage of Qt? ie we would not support non-exclusive radiobuttons, and if some crazy person wants to use them, they would have to go outside of magicgui. I'm very much ok with being permanently opinionated here.

Alternative is to edit wikipedia along with adding non-exclusive support. 😂

**Comment by tlambert03** [comment]
I don't know how many different ways I can say "I agree" here before everyone sees there's no disagreement! 😂  radio groups already were imposing exclusivity, and I'm happy to keep it that way.  Again, I was only providing context
