### ISSUE TITLE
Display slider current value and range min/max in the magicgui widget

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/magicgui#19]
I've been doing some work involving magicgui, and have noticed that sliders don't show any indication of what value currently is selected.

For a minimal working example, in [napari_parameter_sweep.py](https://magicgui.readthedocs.io/en/latest/examples/napari_parameter_sweep/) the image updates but the slider doesn't show any indication of what the current selected value is, or for that matter the min & max of the slider range (you'd have to go digging in the code for that). This is less than ideal for a parameter sweep, where you want to be able to make a note of what the best values were at the end.

**Comment by schoinh** [comment]
It would amazing if the display of current value was editable, like a spinbox that is synced with a slider.
