### ISSUE TITLE
Update widget interactively

### ISSUE THREAD

**Issue by ViktorvdValk** [napari/magicgui#190]
Is it possible to update a widget based on user input in the widget?
I would like to extend the widget input options based on a box (boolean) selected by the user.
For the elastix registration app I would like to add an option: "Use masks"
If selected the widget should contain two extra mask loaders, but if not selected these loaders (image dropdowns in napari) shouldn't be there.

**Comment by tlambert03** [comment]
You can connect the `widget.use_masks.changed` event to a function that sets the `widget.mask.visible` attribute:

```python
from magicgui import magic_factory

def connect_events(widget):
    def toggle_mask_widgets(event):
		# the event has an attribute `.value` that
		# will contain whether the button was checked or not
        widget.mask_a.visible = event.value
        widget.mask_b.visible = event.value
	
	# when use_masks changes, pass the event
	# to `toggle_mask_widgets`
    widget.use_masks.changed.connect(toggle_mask_widgets)
    # avoid layout reflow on toggle...
	# currently only possible with backend API
	widget.native.layout().addStretch()

@magic_factory(widget_init=connect_events)
def factory(use_masks: bool = True, mask_a="", mask_b=""):
    pass

widget = factory()
widget.show(run=True)
```

**Comment by tlambert03** [comment]
Going to close this (since it looked like you've got something working), but don't hesitate to reopen
