### ISSUE TITLE
Add range slider

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#192]
we need a range slider.  Could port the one from napari, or perhaps look into other implementations out there ([qt-range-slider](https://github.com/introkun/qt-range-slider) could be promising, but it still depends on PyQt5... there is an open request to use qtpy.)

**Comment by sofroniewn** [comment]
@DragaDoncila see this issue, it could be something great for you to add to magicgui :-)

**Comment by tlambert03** [comment]
closed by #455
