### ISSUE TITLE
Feature request: support for QFileDialog (file and directory choosers)

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/magicgui#20]
One very common component of GUIs I build for users is a file or directory chooser. The use case is usually:
* select the input data (might be a folder full or images, or sometimes a single input file)
* select a folder where you want to save the output results
* tell me what other parameters you want to use for the analysis

There is [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html), which I think would fulfill this use case.

**Comment by tlambert03** [comment]
That’s sounds good.  What should the argument type be for magicgui to render a dialog like this?  Maybe pathlib.Path?

```python
@magicgui
def func(path: pathlib.Path):
    ...
```

**Comment by tlambert03** [comment]
@GenevieveBuckley ... any chance you want to get your hands dirty and submit a PR for this?  I can definitely direct you to the appropriate places

**Comment by tlambert03** [comment]
here's roughly what needs to be done (all in `magicgui/_qt.py`):
- add a mapping from `pathlib.Path` to `QFileDialog` in the `type2widget` function
- add an `elif isinstance(widget, QFileDialog):` section to `getter_setter_onchange`, and then choose which methods from QFiledialog to use as the "getter", "setter", and "on_change" signal. (follow the pattern for the others)
- lastly, we'll probably need to make our own QFileDialog subclass that has some things set to make it work inside other widgets... minimally something like:

```python
from qtpy.QtCore import Qt, QFileDialog

class MagicFileDialog(QFileDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setOption(QFileDialog.DontUseNativeDialog)
        self.setWindowFlags(self.windowFlags() & ~Qt.Dialog)
```
(and then, actually, use `MagicFileDialog`  in the `type2widget` map.

we may want to further customize that FileDialog once we play with it a bit (for instance... but removing the open button?)

**Comment by GenevieveBuckley** [comment]
Thanks Talley! I had a small play around with this last night, I think I need to have more of a look at the getter/setter pattern you have for the other widgets. I'm going to be busy for the next few days but I'll let you know how I go

**Comment by VolkerH** [comment]
Just wondered whether magicgui supports `pathlib.Path` types in combination with file dialogs and the search turned up this issue. 
Just curios how one could enforce:

- selecting a single file only
- selecting multiple files
- selecting a single folder only
- selecting either folder or file

Does it make sense to declare subtypes for this or do any of you have a better idea for this?

**Comment by GenevieveBuckley** [comment]
I suspect so. No, I do not have a better idea for this at this stage (and I do think all of the controls you list are important)

**Comment by GenevieveBuckley** [comment]
Looking a bit more at the docs, the PyQt5 `QFileDialog` has a `FileMode` enumeration, which includes things like `AnyFile`, `ExistingFile`, `Directory`. If we can work out how to pass values through to this enumeration, maybe we can do most of what you want.

**Comment by VolkerH** [comment]
Yep, I saw that as well. I guess yet another option that it needs to have (for files) is input file (I guess that is equivalent `ExisitingFile`):

* input file (therefore must already exist)
* output file (a new name for a non-existing file could be provided by the user)

So if a separate type for all possible combinations of these flags was required that would be rather cluttered.
Hmmm. Don't really have a better idea though either.

**Comment by VolkerH** [comment]
Maybe the `Annotated` type could help here, with the type of file selection behaviour passed as an annotation. https://www.python.org/dev/peps/pep-0593/

**Comment by tlambert03** [comment]
Thanks for the great discussion.  I agree it's all important.  @GenevieveBuckley, I pushed a PR to your fork for #23 that proposes a "mode" option for magicgui.  Works like this:

```python
@magicgui(filename={"mode": "existing_file"})
def filepicker(filename=Path("~")):
    ...
```

The mode corresponds to one of these four options (via an internal Enum), which in turn correspond to one of these four static methods of the QFileDialog:
`EXISTING_FILE` = [getOpenFileName](https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName)
`EXISTING_FILES` = [getOpenFileNames](https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileNames)
`OPTIONAL_FILE` = [getSaveFileName](https://doc.qt.io/qt-5/qfiledialog.html#getSaveFileName)
`EXISTING_DIRECTORY` = [getExistingDirectory](https://doc.qt.io/qt-5/qfiledialog.html#getExistingDirectory)

the `filter` option can also be passed, which lets you limit selections to a certain file type: e.g:
`{"filter": "Images (*.tif *.tiff)"}`  <- that's Qt syntax for now

> Maybe the `Annotated` type could help here

maybe someday!  but we'll have to wait a while for that to be a complete solution.

**Comment by jni** [comment]
@tlambert03 

> maybe someday! but we'll have to wait a while for that to be a complete solution.

Will we? By NEP-29 we can actually drop Python 3.6 *now*, which means we have access to Annotated through a dependency. Then you could do:

```python
@magicgui
def filepicker(
    filename : Annotated[Path, {'mode': 'existing_file', 'filter': 'Images (*.tif *.tiff)'}]
):
```

?

I also think it might be better to go with r/w for modes (existing file/new file), and Sequence[Path] for existing files. For directories... Maybe a `directory=True` annotation? And then filters potentially should just be plain glob patterns...

**Comment by tlambert03** [comment]
> which means we have access to Annotated through a dependency.

ah cool.  I should have assumed there would be a backport!  That's great, and then extends well beyond the filedialog.  And am I correct in gathering then that pretty much everything we're already doing with [argument-specific and Qt-specific options](https://magicgui.readthedocs.io/en/latest/configuration/#argument-specific-options) could be easily added as `Annotated` types?

I also like r/w mode and `Sequence[Path]`... all very cool!

**Comment by jni** [comment]
> am I correct in gathering then that pretty much everything we're already doing with argument-specific and Qt-specific options could be easily added as Annotated types?

They could, but to be honest I don't think they should. Those Qt-specific options and switching between valid widgets for a given type, and fiddling with *widget* rather than *argument* parameters should be part of the magicgui API, rather than the function signature. But something like narrowing down a type is a perfect use of Annotated imho.
