### ISSUE TITLE
conda recipe

### ISSUE THREAD

**Issue by k-dominik** [napari/magicgui#21]
Hello!

Magicgui looks pretty neat! Would you guys mind to make this available via conda-forge? I have a [recipe](https://github.com/k-dominik/staged-recipes/blob/add-magicgui/recipes/magicgui/meta.yaml) ready that I could make a PR with conda-forge anytime.

Cheers!

**Comment by tlambert03** [comment]
yes please!  Could you add me as a maintainer as well?

**Comment by k-dominik** [comment]
done: https://github.com/conda-forge/staged-recipes/pull/11848
thank you very much!!

**Comment by tlambert03** [comment]
live on [anaconda cloud](https://anaconda.org/conda-forge/magicgui) now.  added to readme. thanks again @k-dominik!
