### ISSUE TITLE
Categorical Widget that allows for Multi-Select

### ISSUE THREAD

**Issue by jluethi** [napari/magicgui#229]
It would be very useful if magicgui had a Widget that allows for multiple selections. E.g. I have an Enum with values `['feature1', 'feature2', 'feature3', 'feature4', 'feature5']` as potential choices and I'd like to select features 1, 2 & 3.

It seems to be possible in QtWidgets, e.g. QListWidget: https://stackoverflow.com/questions/4008649/qlistwidget-and-multiple-selection

Details on the use-case: I'm writing a napari plugin to train a classifier on an image using features from a pandas dataframe. I want to be able to give a list of features to the classifier to use. I can have a drop-down to let the user pick 1 feature, but often the user may want to specify e.g. 3 features to be used or 10 features to be used.

![Bildschirmfoto 2021-05-05 um 20 54 00](https://user-images.githubusercontent.com/18033446/117194144-069c7e00-ade4-11eb-9574-846a5c9c184c.png)

**Comment by tlambert03** [comment]
Good one!  Will have to make a new widget for it (QComboBox can't have multiple-selection)... but shouldn't be too hard.

**Comment by jluethi** [comment]
Awesome, looking forward to it. Thanks so much for the great responsiveness and all the help!
