### ISSUE TITLE
napari image arithmetic widget - documentation error

### ISSUE THREAD

**Issue by ch-n** [napari/magicgui#230]
**Describe the bug**
The example in the documentation does not function correctly. The error:
`TypeError: Cannot add object with type  to TypedList expecting type (,)`
is raised upon widget execution.

**To Reproduce**
Copy the example from the documentation and run it from terminal.

The example in the git works fine. If I saw it correctly the only difference is this:
doc:
def image_arithmetic(layerA: Image, operation: Operation, layerB: Image) -> **Image**:

git:
def image_arithmetic(layerA: Image, operation: Operation, layerB: Image) -> **ImageData**:

If I import `ImageData` and replace the `Image` the doc example works fine.

Keep up the good work,
Chris

**Comment by tlambert03** [comment]
thanks!  will update
