### ISSUE TITLE
Add "disabled" for widgets

### ISSUE THREAD

**Issue by yliu88au** [napari/magicgui#233]
Thank you for your wonderful work on napari and magicgui. 

I would really like to have a possibility to set a widget "disabled" (ie, grey out, not responsive) in addition to "visible = False". With widgets invisible, GUI may look very strange (areas of empty places).

**Comment by tlambert03** [comment]
It's there already:

```python
from magicgui import magicgui, widgets

@magicgui(field={'enabled': False})
    def widget(field: int): ...

# or
widget = widgets.SpinBox(value=1, enabled=False)
```

or, after widget creation:
```
widget.enabled = False
```

**Comment by yliu88au** [comment]
Thank you so much. Next time, I should check carefully first.

**Comment by tlambert03** [comment]
no worries!  it's always ok to ask :)
