### ISSUE TITLE
Get paremeters entered by a widget

### ISSUE THREAD

**Issue by malj390** [napari/magicgui#239]
Hello,

After tweaking the parameters, I would like to know if it is possible to get the values back entered in the widget?

I suspect that it is in
``` viewer.window ```
But not sure then in which subsection could be.

Thank you

**Comment by tlambert03** [comment]
Please have a look through the QuickStart guide: https://napari.org/magicgui/usage/quickstart.html

Setting and retrieving values programmatically is covered there

**Comment by tlambert03** [comment]
(`viewer.window` is a napari thing.  While magicgui is works well with napari, it is independent of napari.  So you'll want to look at the widget itself for these things)

**Comment by malj390** [comment]
Hi @tlambert03, I'm having trouble understanding how to extract the parameters from a function decorated in napari. I know how to extract them like this:

```
from inspect import signature
from magicgui.widgets import Container
from magicgui.widgets import create_widget

def my_function(x='hello', y=400):
  ...

params = signature(my_function).parameters.values()
container = Container(
    widgets=[create_widget(p.default, name=p.name) for p in params]
)
container.show()

container_values = {i.label: i.value for i in container._list}
container_values
```

But when I do this:
```
from napari.types import LabelsData, ImageData, LayerData
from napari.layers import Layer
from skimage import restoration

from inspect import signature
from magicgui.widgets import Container
from magicgui.widgets import create_widget

@magicgui(call_button='Run Gaussian', auto_call=True, result_widget=False, )
def gaussian(image: ImageData, sigma: np.float64 = 1) -> ImageData:
    """Threshold an image and return a mask."""
    result = filters.gaussian(image, sigma)
    result = (result / np.max(result))*100
    return result

viewer = napari.view_image(im)
viewer.window.add_dock_widget(gaussian, area = 'right', name='gaussian')

# From this part I'm just trying out because not sure how objects relate here.
w1 = gaussian()
params = signature(gaussian).parameters.values()
```
I get an odict object, and I don't understand how to access the parameters from there.

Thanks in advance

**Comment by tlambert03** [comment]
you don't need to use inspect.signature here, just access them directly on the widget itself

```python
@magicgui
def gaussian(image: ImageData, sigma: np.float64 = 1) -> ImageData:
    ...

# current image and sigma values accessible at:
gaussian.image.value
gaussian.sigma.value
```

reminder, after you decorate a function with `@magicgui` ... the function name _is_ the widget.
The specific part of the quickstart I was referring to is [here](https://napari.org/magicgui/usage/quickstart.html#two-way-data-binding).

**Comment by tlambert03** [comment]
another tip: If you want a dict of parameters like you have in your first example, the magicgui object has a `__signature__` attribute that behaves like an inspect signature object that stays up to date:

```python
In [1]: from magicgui import magicgui
   ...:
   ...: @magicgui
   ...: def gaussian(image: int, sigma: float = 1) -> int:
   ...:     ...
   ...:

In [2]: gaussian.sigma.value = 3

In [3]: {k: p.default for k,p in gaussian.__signature__.parameters.items()}
Out[3]: {'image': 0, 'sigma': 3.0}
```

**Comment by malj390** [comment]
> ```python
> from magicgui import magicgui
>    ...:
>    ...: @magicgui
>    ...: def gaussian(image: int, sigma: float = 1) -> int:
>    ...:     ...
>    ...:
> 
> In [2]: gaussian.sigma.value = 3
> 
> In [3]: {k: p.default for k,p in gaussian.__signature__.parameters.items()}
> Out[3]: {'image': 0, 'sigma': 3.0}
> ```

The line [2] works well when I do it like that but my purpose is to get the gaussian.sigma.value after I changed it in the Napari window and clicked run. And then close the window.

Thanks

**Comment by tlambert03** [comment]
I understand, line [2] was just an example... it also works if you change it in the gui:


https://user-images.githubusercontent.com/1609449/123256719-4700aa00-d4bf-11eb-9c81-ea09e7ae6817.mov

**Comment by malj390** [comment]
Oh interesting. I just  I can discovered what is happening, but not sure how to solve it.

I run it in jupyter lab and while the window is open I can re run the line with gaussian.sigma.value and it pops out the proper updated result. Also with the dictionary trick. But when I close the window, this happen.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-320781febf9e> in <module>
----> 1 gaussian.sigma.value
      2 # dict_param = {k: p.default for k,p in gaussian.__signature__.parameters.items()}
      3 dict_param

~\anaconda3\envs\napari-env\lib\site-packages\magicgui\widgets\_bases\value_widget.py in value(self)
     69                     ) from e
     70             return self._bound_value
---> 71         return self.get_value()
     72 
     73     @value.setter

~\anaconda3\envs\napari-env\lib\site-packages\magicgui\widgets\_bases\value_widget.py in get_value(self)
     52         bound to self._bound_value.
     53         """
---> 54         return self._widget._mgui_get_value()
     55 
     56     @property

~\anaconda3\envs\napari-env\lib\site-packages\magicgui\backends\_qtpy\widgets.py in _mgui_get_value(self)
    153 
    154     def _mgui_get_value(self) -> Any:
--> 155         val = getattr(self._qwidget, self._getter_name)()
    156         return self._post_get_hook(val)
    157 

RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted```

I also try to store the gaussian.sigma.value in a new variable so it will be stored automatically but it doesn't. So to have the parameter updated it is required to run the line manually.

**Comment by tlambert03** [comment]
here's an example inside of napari: 

https://user-images.githubusercontent.com/1609449/123257402-19683080-d4c0-11eb-9506-4117aae0da55.mov


let me know if I'm missing something?

**Comment by tlambert03** [comment]
> RuntimeError: wrapped C/C++ object of type QDoubleSpinBox has been deleted```

yeah, when you close the widget, it gets destroyed... maybe you can elaborate a bit on your use case?  You'd like to create a widget, get some feedback, close the widget and then use the value?

**Comment by malj390** [comment]
My purpose is to have a set of widgets that use different "outputs" of the other widgets. Once the parameters of the different widgets are set, close and have those settings store so they can be used for bulk processing of the same type of images. 
Example: Raw image -> Gaussian -> Thresholding. Then have all the parameters stored automatically before closing the window.

**Comment by tlambert03** [comment]
you could connect the `widget.changed` event to a function that stores your parameters:


```python
from magicgui import magicgui

PARAMS = {}

@magicgui
def func(param1: int, param2: str): ...


@func.changed.connect
def store_params(event):
    widget = event.value
    PARAMS[widget.name] = {
        n: p.default for n, p in widget.__signature__.parameters.items()
    }


func.show(run=True)
# this will only print after you close the widget
print(PARAMS)
```

you might also be interested in looking through some of the code we did in https://github.com/clEsperanto/napari_pyclesperanto_assistant (which is a similar pipeline of processing using magicgui for input).  Basically, the user interactively sets up a chain of processing events using magicgui widgets.  Then the task graph can be collected using the `to_dask` method [here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/cbaa060335d6b963bbea92cfee3594360a1ce91e/napari_pyclesperanto_assistant/_gui/_Assistant.py#L149) ... which outputs a [dask task graph](https://docs.dask.org/en/latest/graphs.html) representing the functions and their arguments...

**Comment by malj390** [comment]
@tlambert03 your last advise of pyclesperanto is amazing!! Thanks

I'm getting an error when trying to save the pipeline, any clues how could I fix this?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\users\User\anaconda3\envs\napari-env\lib\site-packages\napari\_qt\containers\_layer_delegate.py in paint(self=, painter=, option=, index=)
     79         # update the icon based on layer type
     80 
---> 81         self.get_layer_icon(option, index)
        self.get_layer_icon = >
        option = 
        index = 
     82         # paint the standard itemView (includes name, icon, and vis. checkbox)
     83         super().paint(painter, option, index)

c:\users\User\anaconda3\envs\napari-env\lib\site-packages\napari\_qt\containers\_layer_delegate.py in get_layer_icon(self=, option=, index=)
     92             icon_name = 'folder-open' if expanded else 'folder'
     93         else:
---> 94             icon_name = f'new_{layer._type_string}'
        icon_name = undefined
     95 
     96         icon = QColoredSVGIcon.from_resources(icon_name)

AttributeError: 'NoneType' object has no attribute '_type_string'
```
Thanks again

**Comment by GiorgiaTortora** [comment]
> you don't need to use inspect.signature here, just access them directly on the widget itself
> 
> ```python
> @magicgui
> def gaussian(image: ImageData, sigma: np.float64 = 1) -> ImageData:
>     ...
> 
> # current image and sigma values accessible at:
> gaussian.image.value
> gaussian.sigma.value
> ```
> 
> reminder, after you decorate a function with `@magicgui` ... the function name _is_ the widget. The specific part of the quickstart I was referring to is [here](https://napari.org/magicgui/usage/quickstart.html#two-way-data-binding).

@tlambert03 
Hello!
Is it possible to do something like that but using the @magic_factory decorator instead of the @magicgui? I created two widgets using @magic_factory and I want to pass the parameter obtained in the first one (obtained in the way you showed gaussian.sigma.value) to the second one, but it seems that with the @magic_factory decorator it's not possible.

Thak you for your help!

**Comment by tlambert03** [comment]
can you show me how you're doing it?  once the widgets are created by calling the factory, the resulting widget _should_ behave exactly like any other widget.  an example would be helpful

**Comment by GiorgiaTortora** [comment]
I create the first widget in this way:

@magic_factory(call_button="Register ROIs",
          mode={"choices": ['Translation','Affine','Euclidean','Homography']})
def register_rois(viewer: Viewer, image: Image,
                    labels_layer: Labels,
                    mode: str = 'Translation',
                    median_filter_size:int = 3,
                    scale = 0.5,
                    bbox_zoom = 1,
                    register_entire_image:bool = False,
                    show_registered_stack:bool = False,
                    initial_time_index:int = 0,
                    ):

where at a certain point there is:

register_rois.initial_time_index.value = initial_time_index

Then, out of this widget, I define a function in which I want to use register_rois.initial_time_index.value = initial_time_index:

def calculate_intensity(image:Image,
                        roi_num:int,
                        points_layer:Points,
                        labels_layer:Labels
                        ):
    ...
    initial_time_index = register_rois.initial_time_index.value

    return intensities, initial_time_index

Finally I create a second widget in which I use the function calculate_intensity:

@magic_factory(call_button="Process registered ROIs")
def process_rois(viewer: Viewer, image: Image, 
                 registered_points: Points,
                 labels_layer: Labels,
                 correct_photobleaching: bool,
                 plot_results:bool = True,
                 save_results:bool = False,
                 path: pathlib.Path = os.getcwd()
                 ):
    ...
    intensities, initial_time_index = calculate_intensity(image, roi_num, 
                                              registered_points,
                                              labels_layer)

But I get this error:

in calculate_intensity  initial_time_index = register_rois.initial_time_index.value
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by tlambert03** [comment]
it's still a bit hard to say from this.  Since you didn't explicitly mention _calling_ your magic_factory decorated function to create a widget, I'll point out that whereas `magicgui` turns a function _into_ a widget (i.e. the name of the function _becomes_ the name of the widget in the local scope)... `magic_factory` turns the function into a function that can be called to create  widgets (i.e. a little "factory" for widgets).

```
@magic_factory
def register_rois():
    ...

my_widget = register_rois()
```

vs

```
@magic_factory
def register_rois():
    ...

# register_rois IS the widget
```

**Comment by GiorgiaTortora** [comment]
I don't explicitly call my magic_factory decorated function to create a widget because I want to create a napari plugin. According to what is written here https://napari.org/plugins/first_plugin.html, to create a widget you just need to add the magic_factory decorator without calling explicitly the magic_factory decorated function. But in this way when in the process_rois widget I call

register_rois.initial_time_index.value

(that belongs to the register_rois widget) I get

 AttributeError: 'NoneType' object has no attribute 'value'. So the register_rois is considered a NoneType object.

Do you think I need to explicitly call my magic_factory decorated function to let things work?

**Comment by tlambert03** [comment]
it would just be so much easier to help if you could give me your full example.

**Comment by GiorgiaTortora** [comment]
Thank you @tlambert03 for your help. Till now, I didn't realize that it is necessary to explicitly call the magic_factory decorated function in order to create the widget . Now I did it in this plugin I created

https://github.com/GiorgiaTortora/napari-roi-registration 

and it seems to work. 
Do you think I created the widgets in the right way using the magic_factory decorator or do you think there is a more Pythonic (Naparonic) way to do it?

Thank you very much for your help.

**Comment by tlambert03** [comment]
The main point here is that, to make a napari widget plugin, you must provide a _callable_ function that returns a widget instance.  That is exactly what magic_factory does.  It turns a function into a new function that, when called, returns a widget.  (by contrast, `@magicgui`, turns the function _into_ a widget instance immediately).

so ...

> Till now, I didn't realize that it is necessary to explicitly call the magic_factory decorated function in order to create the widget . Now I did it in this plugin I created

As **a napari plugin**, it's _not_ necessary for you to explicitly call the `magic_factory` function.  You're just supposed to tell napari where to find that function (as you do in your manifest).

By contrast, if you're _not_ using it as a plugin... but rather directly adding the widget manually to a viewer instance (as you do [here](https://github.com/GiorgiaTortora/napari-roi-registration/blob/d583d600f8aa3a06e628226513bfcb0a3ca9d717/src/napari_roi_registration/_widget.py#L443-L461)), then you _do_ need to call the function to create a widget, before using `add_dock_widget`.

two different use cases.  as a plugin, I'd recommend that you move [these three lines](https://github.com/GiorgiaTortora/napari-roi-registration/blob/d583d600f8aa3a06e628226513bfcb0a3ca9d717/src/napari_roi_registration/_widget.py#L443-L445) into your `if __name__ == '__main__'` block.   that's not something you need to do as a plugin (though, it's something you might do when you are _testing_ your widget by directly/manually adding it to the viewer.   does that make sense?
