### ISSUE TITLE
How to dock a magicgui widget created using the direct widget API?

### ISSUE THREAD

**Issue by Tomaubier** [napari/magicgui#240]
Hi,
While developing a napari plugin, I'm trying to dock a widget created using the [Direct Widget API](https://napari.org/magicgui/usage/direct_api.html) approach. From the demo widget provided [here](https://napari.org/magicgui/usage/direct_api.html), I tried returning the `container` variable in the `napari_experimental_provide_dock_widget()` function however napari seems to expect a callable object as opposed to a non-callable widget object:
```_plugin_manager.py (279): Plugin 'napari-usneutools' provided a non-callable object (widget) to `napari_experimental_provide_dock_widget`: <Container (spin: NoneType = 10)>. Widget ignored.```

Is there a way to dock a widget created in this fashion?

**Comment by tlambert03** [comment]
Hi @Tomaubier... yeah, the main point here is that while napari's `viewer.window.add_dock_widget()` would accept a widget _instance_ (like a `Container` instance), for plugins using `napari_experimental_provide_dock_widget`, we need to be able to create multiple widget instances, and so need more of a factory function or class.

there's two main patterns you can use here:

1) create a custom `Container` subclass, and return the *class* itself  from napari_experimental_provide_dock_widget. So, reworking the example you linked above:

    ```python
    class MyCustomContainer(Container):
        def __init__(self):
            spin_box = SpinBox(value=10, name='spin', label='Value:', max=100)
            file_picker = FileEdit(value='some/path')
            slider = Slider(value=30, min=20, max=40)
            label = Label(value=slider.value)
            slider.changed.connect(lambda e: setattr(label, 'value', e.value))
            super().__init__(widgets=[spin_box, file_picker, slider, label])

    @napari_hook_implementation
    def napari_experimental_provide_dock_widget():
        return MyCustomContainer
    ```

2) create a simple wrapper function, and return the function object:

    ```python
    def make_my_widget():
        spin_box = SpinBox(value=10, name='spin', label='Value:', max=100)
        file_picker = FileEdit(value='some/path')
        slider = Slider(value=30, min=20, max=40)
        label = Label(value=slider.value)
        slider.changed.connect(lambda e: setattr(label, 'value', e.value))
        return Container(widgets=[spin_box, file_picker, slider, label])

    @napari_hook_implementation
    def napari_experimental_provide_dock_widget():
        return make_my_widget
    ```

**Comment by Tomaubier** [comment]
Awesome! Thanks for your quick feedback!
