### ISSUE TITLE
`magic_factory` arguments get lost after the first call

### ISSUE THREAD

**Issue by brisvag** [napari/magicgui#241]
**Describe the bug**

Some arguments to `magic_factory` seem to be lost after the first instantiation. I found this problem with `widget_type`, but not for `call_button`, so I'm not sure how common it is.

**To Reproduce**
```python
@magic_factory(x={'widget_type': 'Slider'})
def factory(x=1):
    ...

w1 = factory()
w2 = factory()
w1.show()
w2.show()
```
The second widget does not use a slider, but a spinbox (default), and so will all the subsequent widgets.

**Expected behavior**
Each `FunctionGui` generated by the factory should be exactly the same.

**Screenshots**

![image](https://user-images.githubusercontent.com/23482191/125100183-19c81480-e0d9-11eb-8855-1dd19dcdb88e.png)

**Environment (please complete the following information):**
 - OS: Linux
 - backend: QT5
 - magicgui version: 0.2.9

**Comment by tlambert03** [comment]
thanks.  this was addressed in https://github.com/napari/magicgui/pull/224, but I'm realizing now that it hasn't been released?  Can you test on master?

**Comment by brisvag** [comment]
Oh! I only searched the issues, so I missed that :) Yeah, master works just fine, so this can be closed!

**Comment by tlambert03** [comment]
thanks for checking.  I'll release this week
