### ISSUE TITLE
No event when selection of --- (None) when using Optional annotation

### ISSUE THREAD

**Issue by Czaki** [napari/magicgui#260]
**Describe the bug**

When using `Optional` annotation for ComboBox then change on `--` value does not fire `changed` event when selecting of value cause such event

**To Reproduce**

Here example of code, base on the base `Layer` registration code.   

```python
from typing import Optional

from magicgui import register_type
from magicgui.widgets import create_widget, Label, Container
from qtpy.QtWidgets import QApplication

def get_choices(gui):
    return ["aa", "bb", "cc"]

def get_callback(gui, result, return_type):
    print(result)
    return 1


def check_connect(event):
    label.value = choice.current_choice
    print(event)


class ExampleClass:
    pass

register_type(ExampleClass, choices=get_choices, return_callback=get_callback)



app = QApplication([])
choice = create_widget(annotation=Optional[ExampleClass])
choice.changed.connect(check_connect)
label = Label()
Container(widgets=(choice, label)).show()

app.exec_()
```

**Expected behavior**

The event should be emitted.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux
 - backend: Qt 5.15.4
 - magicgui version 0.2.10

**Comment by tlambert03** [comment]
thanks for the clear example.  fixed in #263
