### ISSUE TITLE
Error when annotating arguments with Optional[Dict]

### ISSUE THREAD

**Issue by jni** [napari/magicgui#269]
**Describe the bug**

I don't have a minimum reproducible example yet. I don't think it'll be hard to produce but wanted to get something written down. When annotating an argument with "Optional[Dict] = None", I get an error from issubclass in this line:

https://github.com/napari/magicgui/blob/481f665af1992c0c99eabe4d608e1d0b6da78e54/magicgui/type_map.py#L85-L86

It tries to evaluate `issubclass(typing.Dict, type(None))`, which fails with:

```pytb
TypeError: issubclass() arg 1 must be a class
```

Changing the annotation to `Optional[dict]` (no typing) bypasses the error.

**Environment:**
 - OS: Mac
 - backend: PyQt5
 - magicgui version 0.2.10/master

**Comment by tlambert03** [comment]
ok thanks!
