### ISSUE TITLE
Update Pushbutton label synchronizing with napari

### ISSUE THREAD

**Issue by NeversayEverLin** [napari/magicgui#273]
I am working to integrate magicgui into napari. I create a dock widget inside napari. I have a pushbutton inside. Now, I want to change the label display and also value of pushbutton every time the button is pushed. Like, when button pushed, the display label on button will be changed between 'connect' and 'disconnect'. 
Here is my code. However, even though the event.value changed, the pushbutton's value and dislabel never update in napari and also in its own value. Could someone help me figure it out? Thanks. 

```py
import napari 
from skimage import data 
from magicgui import widgets 

def tryme(event):
    print("Before event is {}".format(event.value))
    print("Before Button {}".format(event._sources[0].value))
    if event.value == False:
        event._sources[0].value = 1 
        event._sources[0]._qwidget.setText("Connect")
        print(event._sources[0].text)
        event.value = True 
    else:
        event._sources[0].value = 0 
        event._sources[0]._qwidget.setText("Disconnect")
        print(event._sources[0].text)
        event.value = False
    print("After event is {}".format(event.value))
    print("After Button {}".format(event._sources[0].value))
    return event._sources[0]

if __name__ == "__main__":
    viewer = napari.Viewer()

    wSetPowerLevel = widgets.FloatSlider(name="setPowerLevel",value=10,max=100,label="Power level(%)",min=0,step=0.1)
    wSetLowerBandwidth = widgets.FloatSlider(name="setLowerBandwidth",value=400,max=700,label="Lower BW(nm)",min=400,step=0.1)
    wSetUpperBandwidth = widgets.FloatSlider(name="setUpperBandwidth",value=1200,max=2000,label="Upper BW(nm)",min=1200,step=0.1)
    wTimeOut = widgets.Label(name="Timeout (s)",value="0.5",label="Timeout(s)")
    wStatus  = widgets.Label(name="Status",value="Not connected",label="Status")
    wVariaStatus = widgets.Label(name="VariaStatus",value="Not connected",label="VariaStatus")
    wConnect = widgets.PushButton(name="Connect",tooltip="connect or disconnect from laser",value=0,text="Connect")
    wEmission = widgets.PushButton(name="Emission",tooltip="set laser emission",value=0,text="Emission Off")
    wResetInterlock = widgets.PushButton(name="ResetInterlock",tooltip="reset laser interlock",value=0,text="Reset Interlock")
    
    wConnect.changed.connect(tryme)
    container = widgets.Container(widgets=[wSetPowerLevel,wSetLowerBandwidth,wSetUpperBandwidth,wTimeOut,wStatus,wVariaStatus,wConnect,wEmission,wResetInterlock],name="Laser Control",label="Laser Control")
    viewer.window.add_dock_widget(container,name="Laser Control",add_vertical_stretch=True)
    napari.run()
```

**Comment by tlambert03** [comment]
you could replace your `tryme` function and the `wConnect.changed.connect(tryme)` statement with this (don't use all those private event attributes... it will fail eventually):

with 
```py
wConnect.is_connected = False
@wConnect.changed.connect
def _on_connect(event):
    wConnect.is_connected = not wConnect.is_connected
    wConnect.text = 'Disconnect' if wConnect.is_connected else 'Connect'
```

**Comment by NeversayEverLin** [comment]
> you could replace your `tryme` function and the `wConnect.changed.connect(tryme)` statement with this (don't use all those private event attributes... it will fail eventually):
> 
> with
> 
> ```python
> wConnect.is_connected = False
> @wConnect.changed.connect
> def _on_connect(event):
>     wConnect.is_connected = not wConnect.is_connected
>     wConnect.text = 'Disconnect' if wConnect.is_connected else 'Connect'
> ```

Thanks. I works very well! But, BTW, how do I know the decorator for each one of the widgets? for example, if I also want to do something to track the changes whenever Slider value has been modified? Thanks a lot.

**Comment by tlambert03** [comment]
all `ValueWidgets` have a `changed` event that can be connected to: https://napari.org/magicgui/usage/widget_overview.html#valuewidget

so you could do this with any of your slider widgets:

```py
@wSetPowerLevel.changed.connect
def _on_power_change(event):
    print(f'the power changed to {event.value}')
```

**Comment by NeversayEverLin** [comment]
Thanks very much! I got it.

**Comment by tlambert03** [comment]
you're welcome :)
