### ISSUE TITLE
no call button label for magicgui on bound method 

### ISSUE THREAD

**Issue by alisterburt** [napari/magicgui#275]
**Describe the bug**
Not sure if this is a bug or just out of normal use case... the call button label is not appearing correctly when magicgui decorator is used on a bound method rather than a function

**To Reproduce**
The following in ipython with %gui qt shows a button with 'run' rather than 'my_func'

```python
ifrom magicgui import magicgui

class MyObject:
    @magicgui(call_button='my_func')
    def my_func(self):
        print('something')

my_object = MyObject()

my_object.my_func.show()

```

**Expected behavior**
Call button should be called 'my_func'

**Screenshots**
![image](https://user-images.githubusercontent.com/7307488/130321558-05151b84-d632-43b2-9114-43c734a57cb1.png)

**Environment (please complete the following information):**
 - OS: mac
 - magicgui version 0.2.10

**Comment by tlambert03** [comment]
> Not sure if this is a bug or just out of normal use case...

both! :) I agree that should work though.  will take a look
