### ISSUE TITLE
non-gui parameters in decorated functions?

### ISSUE THREAD

**Issue by Borchardt** [napari/magicgui#279]
Hi!

It seems to me that it would be useful to be able to pass non-GUI parameters to magicgui functions. In particular, I would like to be able to pass layer data to my functions without creating or relying on a user facing layer dropdown.

I've done some looking through the documentation and a little bit of code tinkering, but I haven't found a way to make this happen. If it's not currently supported, is it something that you think might be useful?

**Comment by Borchardt** [comment]
Thanks for your response! From my tinkering, it looks like the `bind` parameter does work for getting around the layer dropdown. Unfortunately, it also seems to break autocall functionality: as best as I can tell, updates to data in one layer don't trigger functions with parameters bound to that layer. No big deal, though; appreciate your help anyway!

**Comment by tlambert03** [comment]
> it also seems to break autocall functionality

yep, that's a different issue, but also solvable.  You can think of "bind" as telling magicgui that you'd like to handle that parameter on your own.  From magicgui's perspective, the bound value is "constant" (and `widget.value` never gets set internally anymore.  Remember also that `magicgui` knows nothing about napari:  so if you bind some external object (like a napari layer) to a magicgui paramater, magicgui isn't going to try to inspect that object for "change events" that it can listen for.  you need to hook them up yourself.  For instance, if you want to bind a magicgui parameter to a specific layer, *and* call that function whenever the layer data changes:

```py
from napari.layers import Image
from magicgui import magicgui
import numpy as np

my_image = Image(np.random.rand(4, 4))

@my_image.events.data.connect
@magicgui(image={'bind': my_image})
def func(param: int = 3, image=None):
    print("calling", image.data)

func.show()
```

**Comment by Borchardt** [comment]
Ah, awesome! I had to make a couple of minor modifications to my decorators and signatures to handle the incoming events, so mine ended up looking like:
```
@my_image.events.data.connect
@magicgui(image={'bind': my_image}, event={'bind}': None)
def func(event: None, param: int = 3, image=None):
```
With that done, things are now working as I had hoped. Thanks again for your help!

**Comment by tlambert03** [comment]
Ahh, right, good point.  You could also use a lambda (and not a decorator) to swallow the event object passed by the image data event:

`my_image.events.data.connect(lambda e: func())`

Going to close this now but let me know if anything else comes up!
