### ISSUE TITLE
`@magicgui` parameter options are ignored for class methods.

### ISSUE THREAD

**Issue by hanjinliu** [napari/magicgui#281]
**Describe the bug**
Since I'm extending `magicgui` in [magic-class](https://github.com/hanjinliu/magic-class) recently, I usually combine `magicgui` with class methods. I found parameter options like `{"widget_type": "Slider"}` is ignored if I decorate class methods with `@magicgui`.

**To Reproduce**

This code creates a `FunctionGui` with initial value "a=0":

```python
from magicgui import magicgui

class C:
    @magicgui(a={"value":2})
    def func(self, a:int):
        print(a)
c = C()
c.func
```

while this code works fine:

```python
@magicgui(a={"value":2})
def func(a:int):
    print(a)
func
```

Apparently, it is caused by wrong signature:

```python
c.func.__signature__.parameters
```
```
Out:
mappingproxy({'self': <MagicParameter "self=<__main__.C object at 0x00000284B78ABEE0>" {'enabled': True, 'visible': False}>,
              'a': <MagicParameter "a: int = 0" {'enabled': True, 'visible': False, 'min': 0, 'max': 1000, 'step': 1}>})
```

In the normal case:

```python
func.__signature__.parameters
```
```
Out:
mappingproxy({'a': <MagicParameter "a: int = 2" {'enabled': True, 'visible': False, 'min': 0, 'max': 1000, 'step': 1}>})
```

**Expected behavior**
`FunctionGui.__get__` method says it should be correctly applied to class methods.

**Environment (please complete the following information):**
 - OS: Windows
 - backend: pyqt 5.12.3
 - magicgui version 0.2.10

**Comment by tlambert03** [comment]
can you try master (with https://github.com/napari/magicgui/pull/276) and let me know if you still have it?

**Comment by tlambert03** [comment]
btw, magic class looks awesome!  Would you want to discuss adding it directly to magicgui?

**Comment by hanjinliu** [comment]
Thank you for your quick reply, @tlambert03 !
In the main branch those problem was solved. Sorry for not confirming the recent issues.

I'm happy to integrate it into magicgui! Let's talk about that in zulip or somewhere.

**Comment by tlambert03** [comment]
thanks for checking.  will cut a new release soon, and will follow up on zulip.
thanks for the report!
