### ISSUE TITLE
Better Table widget UI

### ISSUE THREAD

**Issue by hanjinliu** [napari/magicgui#288]
I have personally extended the table widget and I think some of the features should also be integrated into magicgui's `Table` widget:

- Float values are replaced to "...", which makes it inconvenient as a table viewer &rarr; This can be solved by overriding `displayText` method of `QStyledItemDelegate`.
- Column width should be automatically and/or interactively resizable &rarr; `QTableWidget.resizeColumnsToContents()` and `QHeaderView.setSelectionResizeMode(QHeaderView.Interactive)` are useful for this purpose.
- Change editability of table data using `editable` setter &rarr; `QTableWidget.setEditTriggers(QTableWidget.NoEditTriggers)`
- Make table header editable? &rarr; This is a little bit tricky but temporal `QLineEdit` can do this.

Are there any plan of update like these? Since I already have a prototype of these features in [my repo](https://github.com/hanjinliu/impy/blob/main/impy/viewer/widgets/table.py), I think I can help.

**Comment by tlambert03** [comment]
Hey @hanjinliu, sorry for the delay.  Yes I agree, there's some good low-hanging fruit for enhancing the Table widget.

I don't have any immediate plans for the points you listed here.  so would definitely welcome any PRs to this effect!

**Comment by tlambert03** [comment]
hey @hanjinliu ... which, if any of these, still need to be addressed after #301 ?

**Comment by hanjinliu** [comment]
Hi @tlambert03,
I think it's fine now. Sorry for leaving this issue open.

**Comment by tlambert03** [comment]
no worries!  thanks again for the improvements.
I guess the one kind of remaining is still

> Make table header editable? → This is a little bit tricky but temporal QLineEdit can do this

right?

**Comment by hanjinliu** [comment]
yeah, but it seems there are not so much demand for editing headers? Maybe it's safer to keep them non-editable.
