### ISSUE TITLE
how to get an interactive widget to run

### ISSUE THREAD

**Issue by pr4deepr** [napari/magicgui#305]
Hi
  I would like to use magicgui to accept multiple variables from the user and then run an operation. 
For example:

```
from magicgui import magicgui, use_app

@magicgui(call_button="Calculate")
def add(a: int, b: int) -> int:
    result = a + b
    print(f"{a} + {b} = {result}")
    return result

add.show()
use_app('qt').run()
```
I would like the 

- GUI to accept 3 variables
- user presses Calculate and then 
- the function will be executed.

When I run this, nothing happens, unless I use auto_call, but I want it to run when the user clicks a button.
I did see documentation on using `.connect` , but how do I implement that here within the function?

It actually for a post I made on imagesc forum, but thought this is more a magicgui question and not image analysis specifically.
https://forum.image.sc/t/developing-mouse-atlas-addition/58996/14?u=pr4deepr

Cheers
Pradeep

**Comment by adamltyson** [comment]
> thanks for that info! @adamltyson... have you seen anything funny like this with cellfinder recently? There were some big changes with magicgui in the last couple weeks, but I wouldn't expect it to cause this. (sidenote @adamltyson... you _might_ see a lot of warnings in your code now when running magicgui, happy to help clean those up)

@tlambert03  yep, I have seen a few problems with it, and seems to be env specific. I haven't had time to look into this (or the magicgui warnings), I'll have some help to push this forward soon, so I'll probably be back in touch then if we have any issues.
