### ISSUE TITLE
Dynamic containers for workflow creation

### ISSUE THREAD

**Issue by SebastienTs** [napari/magicgui#307]
I would like to implement a sort of dynamic workflow where each step would be a widget container holding its own parameters, and these containers would in turn be held in a "super" container making up the workflow. 

The user should be able to add and remove steps dynamically and there would a sequential dependence between the steps where the choices available for some of the parameters of a given step would depend on the configuration of previous steps. For this, one would need to dynamically retrieve the parameter values from all the widgets inside the previous containers. 

It would also be needed to dynamically add/remove/insert widgets inside a container (instead of destroying and creating everything from scratch each time the workflow is updated).

Also, the step containers would ideally be instantiated from a set of templates (one for each kind of step). Even though one could think of a generic template with the step type encoded as a widget.

Regarding these templates, when using magicgui function decorators in Napari, is it possible to instantiate several dockable widgets from the same function (that would act as template)? When trying this the program does not crash but the latest dockable widget instantiated "steal" all the gui elements from the previous one (empty widgets left).

**Comment by tlambert03** [comment]
hi @SebastienTs, this should be very possible... though is partially outside of the scope of magicgui and will require a little additional "infrastructure".  some thoughts/tips:

> The user should be able to add and remove steps dynamically and there would a sequential dependence between the steps where the choices available for some of the parameters of a given step would depend on the configuration of previous steps.

There's a number of ways to set something like this up, have a look at the [chaining example](https://github.com/napari/magicgui/blob/main/examples/chaining.py) for a 3-step workflow (A->B->C) where changing the parameters in any one widget trigger the downstream widgets to run.

We set up something roughly like this in napari-pyclesperanto-assistant.  New widgets are added [here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/3aea7d854af0418ad6caf497cdafb47cfd6a6784/napari_pyclesperanto_assistant/_gui/_Assistant.py#L127).  there a (magicgui-external) object that tracks all of the widget instances [here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/3aea7d854af0418ad6caf497cdafb47cfd6a6784/napari_pyclesperanto_assistant/_gui/_Assistant.py#L141), and an example of "exporting" that series of interdependent tasks to a dask task graph is [here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/3aea7d854af0418ad6caf497cdafb47cfd6a6784/napari_pyclesperanto_assistant/_gui/_Assistant.py#L178).

> For this, one would need to dynamically retrieve the parameter values from all the widgets inside the previous containers.

it's easy to grab the current state of a widget using the widget.__signature__.  This is an instance of inspect.Signature that holds the current state of the widget as a function signature:

```py
from magicgui import magicgui

@magicgui
def f(x: int, y: int): ...

{k:v.default for k,v in f.__signature__.parameters.items()}
#{'x': 0, 'y': 0}
```

> It would also be needed to dynamically add/remove/insert widgets inside a container (instead of destroying and creating everything from scratch each time the workflow is updated).

No problem, make a [Container](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.Container.html?highlight=container) widget.  This behaves like a simple list of widgets (you can insert and append, etc...).  As you append/insert/pop/remove widgets they'll be added/removed from your container widget.

```py
from magicgui.widgets import Container

c = Container()
c.append(f)  #  widget from above 
c.show()
```

> Regarding these templates, when using magicgui function decorators in Napari, is it possible to instantiate several dockable widgets from the same function (that would act as template)?

They key here is recognize that the `magicgui.magicgui` is a function that turns the provided function into a (single) widget _instance_.  If you want to make multiple widget instances from a single function (template), you have two options:

1) just don't use it as a decorator:

```py
from magicgui import magicgui

def template(x: int, y:int): ...

widget1 = magicgui(template)
widget2 = magicgui(template)
``` 

2) use the `magic_factory` decorator.  apologies, this isn't well documented in the magicgui docs, but there's an example of [using this to make a napari plugin in the napari docs.](https://napari.org/guides/stable/magicgui.html#magic-factory)

```py
from magicgui import magic_factory

@magic_factory
def template(x: int, y:int): ...

widget1 = template()
widget2 = template()
```

**Comment by tlambert03** [comment]
one more tip:

> and these containers would in turn be held in a "super" container making up the workflow.

in addition to creating your own container as I mentioned above, you might look into @hanjinliu's [magic-class](https://github.com/hanjinliu/magic-class), which helps you to compose multiple functions (as class methods) into a super-widget

**Comment by SebastienTs** [comment]
Hi Talley,

Brilliant! I feel like I have a brand new lego box... now to the homeworks :)

The only component I foresee I would still miss is a helper function to save the current state of all the widgets (location, function values...) to file, and another one to restore their state from a file. Has this already been developed by any chance?

Also, this is rather a detail, but I cannot read the value from a magicgui PushButton (which I assume to be true when pushed in an autorun decorated function). This works with RadioButton but they are not as nice for the intended purpose...

Thanks a lot!
S.

**Comment by tlambert03** [comment]
> The only component I foresee I would still miss is a helper function to save the current state of all the widgets (location, function values...) to file, and another one to restore their state from the same file. Has this already been developed by any chance?

well, getting the function values from a widget is like i said above:

```python
def get_state(widget):
    return {k:v.default for k, v in widget.__signature__.parameters.items()}
```

to set the values of a widget given such a dict, 

```py
def apply_state(widget, values):
    for key, val in values.items():
        subwidget = getattr(widget, key)
        subwidget.value = val
```

The position of each widget will depend on your `Container`, so basically, to get the full container state:

```python
state = {widget.name: get_state(widget) for widget in container}
```

I'll leave it to you to figure out saving that and loading it from file :)

> Has this already been developed by any chance?

there is the [`persist` parameter](https://napari.org/magicgui/api/magicgui.html?highlight=persist) in `magicgui()` that is designed to do this ...  but your mileage may vary in this situation

> Also, is there a way to organize all the widgets from an area as tabs (this can be achieved by moving the widgets at the bottom manually) and read which widget is currently active / connect tab changes to a callback?

this sounds like a napari question yes?  Do you mean once you've added widgets as _dock widgets_ to napari?  Assuming yes, you'd have to use `viewer.window._qt_window.tabifyDockWidget`:

https://doc.qt.io/qt-5/qmainwindow.html#tabifyDockWidget

> Finally, this is rather a detail, but I cannot seem to read the value from a magicgui PushButton (which I assume to be true when pushed in an autorun decorated function). This works with RadioButton but they are not as nice for the intended purpose...

the value will only be true while the button is down, but probably won't be true by the time the function is called.   can you elaborate on why you need to access that fleeting "truthy" value?

**Comment by SebastienTs** [comment]
Awesome! I just needed an extra push button to trigger an action that would
be different from the default function action and RadioButtons do not look
great in the UI for this purpose.

Basically it is to apply a function either to the current slice (when any
parameter is tweaked) or to the whole stack when this button is pressed
(without resorting to dask based lazy processing).

I could achieve the same effect if I knew how to figure out if an
auto_update widget function was triggered by its call_button push or by a
parameter change, but I believe that it is not possible...

**Comment by tlambert03** [comment]
can you just `magicgui.widgets.PushButton` to your `Container`, and connect your handler function to the `btn.clicked` signal?  (i.e. the button doesn't _need_ to be from a `@magicgui` generated widget)

**Comment by SebastienTs** [comment]
I see, indeed, the combinations are countless!

**Comment by tlambert03** [comment]
going to close this, to keep open issues under control, but don't hesitate to contact for more help
