### ISSUE TITLE
Pull signature parsing code from MagicGuiBase

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#33]
To better reflect the fact that magicgui is basically just a mapping between types and widgets, I'm thinking that this code that inspects the function signature should be pulled out of the `MagicGuiBase` class:

https://github.com/napari/magicgui/blob/db4c8164915bf63d53cafa476564ec4e5ab78848/magicgui/core.py#L184-L192

and turned into a helper function that accepts a function and returns a dict of parameter names and types.  The base class then can be cleaner, and more of a widget constructor.  This would also make #7 easier, as the base class would just directly accept the types (and it needn't be backed by a function at all).

**Comment by jni** [comment]
I like this. (no surprises. 😜)

**Comment by tlambert03** [comment]
superseded by #43
