### ISSUE TITLE
Event emission of Containers

### ISSUE THREAD

**Issue by hanjinliu** [napari/magicgui#330]
Hi, @tlambert03,

I noticed that value changes in value-widget-like containers such as `SliceEdit` and `FileEdit` are not recognized by `FunctionGui`.
For instance, function is not auto-called in the example below.

```python
from magicgui import magicgui

@magicgui(auto_call=True)
def f(sl=slice(0,10,1)):
    print(sl)

f.show(True)
```

Should it be fixed?

### Environment
```
python==3.9.7
magicgui==0.3.3
psygnal==0.2.0
```

**Comment by tlambert03** [comment]
Yep!  Looks like a bug
