### ISSUE TITLE
auto_call widget decorator does not apply to FileEdit

### ISSUE THREAD

**Issue by SebastienTs** [napari/magicgui#332]
When setting auto_call=True in a widget decorator, the function is not called automatically when the field of a FileEdit GUI element is edited manually or by clicking on the "Select file" button. 

OS: Windows
backend: Qt 5.15.2
magicgui version 0.3.2

**Comment by tlambert03** [comment]
yep, looks like this is fixed now:

```py
import magicgui, pathlib

@magicgui.magicgui(auto_call=True)
def func(path: pathlib.Path):
    print(locals())

func.show(run=True)
```

... prints on change.  h/t @hanjinliu  again for the fix in #331
