### ISSUE TITLE
Advice for nice callback format when lambda is used

### ISSUE THREAD

**Issue by pmascalchi** [napari/magicgui#346]
## ❓ Questions and Help

Hi Talley, regarding https://github.com/napari/magicgui/issues/255, what would be your advice for (future) correct way to write this, that I am currently using with version 0.3.4:

`gui.called.connect(lambda x: gui.close())`

Idea is that it was nice to keep it compact as a single line in the code...

[X] I have searched the [documentation](https://napari.org/magicgui)

**Comment by tlambert03** [comment]
Try new method #2 from that post;

`gui.called.connect(gui.close)`

**Comment by pmascalchi** [comment]
Hi Talley, sorry for coming back with a lot of delay on this.
Thanks for your answer but somehow that doesn't seem to work.

This below works:
`
@magicgui(call_button="Run and Close")
def widget_demo(
    boolean=True,
    number=1,
    string="Text goes here",
    filename=pathlib.Path.home(),
):
    """Run some computation."""
    ...

@widget_demo.called.connect
def my_callback():
    widget_demo.close()

widget_demo.show(run=True)
`

But this doesn't:
`
@magicgui(call_button="Run and Close")
def widget_demo(
    boolean=True,
    number=1,
    string="Text goes here",
    filename=pathlib.Path.home(),
):
    """Run some computation."""
    ...

widget_demo.show(run=True)
widget_demo.called.connect(widget_demo.close())
`

Error is:
Traceback (most recent call last):
  File "D:\PythonCode\Python_scripts\Projects\untitled\MagicGUI_test2_py39.py", line 30, in <module>
    widget_demo.called.connect(widget_demo.close())
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\magicgui\events.py", line 35, in connect
    is_new_style = _new_style_slot(slot)
  File "C:\Users\xxx\AppData\Roaming\Python\Python39\site-packages\magicgui\events.py", line 11, in _new_style_slot
    sig = psygnal._signal.signature(slot)
  File "psygnal\_signal.py", line 877, in psygnal._signal.signature
  File "C:\Program Files\Python39\lib\inspect.py", line 3118, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "C:\Program Files\Python39\lib\inspect.py", line 2867, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "C:\Program Files\Python39\lib\inspect.py", line 2242, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: None is not a callable object

**Comment by tlambert03** [comment]
`widget_demo.called.connect` expects you to pass a function object... but when you call `widget_demo.called.connect(widget_demo.close())` it's as if you did this:

```py
x = widget_demo.close()  # actually *call* close
widget_demo.called.connect(x)  # connect the output of close (which is None)
```

you need `widget_demo.called.connect(widget_demo.close)`

**Comment by pmascalchi** [comment]
I see, that was straightforward, especially the way you explained it.
Thanks a lot!

**Comment by tlambert03** [comment]
gonna close this, but feel free to re-open or post more questions
