### ISSUE TITLE
Unable to relabel CheckBox and RadioButton

### ISSUE THREAD

**Issue by SebastienTs** [napari/magicgui#353]
widget.parameter.label = 'NewLabel' seems to work for all widget types but CheckBox and RadioButton.

Windows, pyqt 5.15.6, magicgui 0.3.4

**Comment by tlambert03** [comment]
This is understandably a little confusing, but the "label" is the bit of text to the _left_ of any widget as it appears in a layout.  Buttons like checkbox and push button (things where the widget _itself_ displays text, unlike, say a spinbox), have an additional parameter `text` (see [here](https://napari.org/magicgui/usage/widget_overview.html#buttonwidget-valuewidget)), so please try `widget.parameter.text = 'whatever'`

**Comment by SebastienTs** [comment]
Awesome!
