### ISSUE TITLE
Glitch in Select widget choices

### ISSUE THREAD

**Issue by SebastienTs** [napari/magicgui#358]
I constantly get a strange glitch where adding a new layer to Napari mess up the choices of a Select widget **in case I have previously programatically modified these choices with such a call**:  widget.param.choices = {some dictionnary}

Is it incorrect to set the choices this way and should I do it differently?

napari: 0.4.13
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.10.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 511.23
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1364x768, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.13
- svg: 0.1.5

**Comment by tlambert03** [comment]
a reproducible example is always greatly appreciated.  I can try to follow what you describe, but it would save me a lot of time if you could give an explicit example of your widget and `{some_dictionary}`.  thanks

**Comment by SebastienTs** [comment]
Here you are. Run this script and create whatever layer type from Napari UI, the choices of the widget get messed up.

```python

import napari
from napari import Viewer
from magicgui import magicgui

@magicgui(
    auto_call=True,
    reg={"widget_type": "Select", 'choices': ' '}
)
def widget_selector(vw: Viewer, reg):
    pass

viewer = napari.Viewer()
dw_inp = viewer.window.add_dock_widget(widget_selector, name="Selector", area='left')

Regions = {'R1': None, 'R2': ((256, 256), (512, 512))}
widget_selector.reg.choices = Regions.keys()

napari.run()

```

**Comment by tlambert03** [comment]
ok, thanks that helps a lot.

The issue here is the same as https://github.com/napari/magicgui/issues/306

The "magic" used behind the scenes to keep a categorical up-to-date with an ever-changing parent widget is proving problematic, and I need to update it to avoid stuff like this.

The solution for you in the short term is to use a _function_ for `choices`:

```py
def get_choices(reg_combo):
    if True:  # whatever logic you need to determine your choices
        Regions = {"R1": None, "R2": ((256, 256), (512, 512))}
        return Regions.keys()
    return [""]


@magicgui(auto_call=True, reg={"widget_type": "Select", "choices": get_choices})
def widget_selector(vw: Viewer, reg):
    pass


viewer = napari.Viewer()
dw_inp = viewer.window.add_dock_widget(widget_selector, name="Selector", area="left")
napari.run()
```

**Comment by tlambert03** [comment]
if it's ok with you, i'd request we close this issue in favor of #306... and I'll try to tackle this soon.

(fwiw, I think your code _should_ work as is)

**Comment by SebastienTs** [comment]
Thanks a lot for the temporary fix! If you have it in the radar somewhere else, I close the issue!
