### ISSUE TITLE
None vs UNSET as default value setting

### ISSUE THREAD

**Issue by gselzer** [napari/magicgui#359]
**Describe the bug**

Some widgets, such as [`RangeEdit`](https://github.com/gselzer/magicgui/blob/9ec44a37bdd0c246d1bd93eba9b1434f61d1190e/magicgui/widgets/_concrete.py#L549), seem to prefer `value=None` upon creation with no starting value. Other widgets like `CheckBox`, who are backed in their instantiation with [`QBaseValueWidget._mgui_set_value()`](https://github.com/gselzer/magicgui/blob/9ec44a37bdd0c246d1bd93eba9b1434f61d1190e/magicgui/backends/_qtpy/widgets.py#L172), seem to instead prefer `UNSET`. This prevents me from writing something like [this](https://github.com/gselzer/magicgui/blob/9ec44a37bdd0c246d1bd93eba9b1434f61d1190e/magicgui/widgets/_function_gui.py#L210) without an error as to the type of widget that is chosen for my return type.

**To Reproduce**

The cleanest way to reproduce this is to checkout [this commit](https://github.com/gselzer/magicgui/commit/9ec44a37bdd0c246d1bd93eba9b1434f61d1190e) on my experimental branch and run `tests/test_return_widgets.py`. To see how changing the `value` of the return widgets affects passing tests, change [this line](https://github.com/gselzer/magicgui/blob/9ec44a37bdd0c246d1bd93eba9b1434f61d1190e/magicgui/widgets/_function_gui.py#L211). Leaving this line in tests `value=None`, removing it will test `value=UNSET`.

**Expected behavior**

I would expect that all widgets prefer one (most likely `UNSET`) over the other.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu, WSL 2 on Windows 11
 - backend: Qt 5.12.3
 - magicgui version 0.3.5

**Comment by tlambert03** [comment]
Hi @gselzer and sorry for the long delay here:

If anything, I'd say this was a slight bug in RangeEdit.  RangeEdit never "preferred" `None`... the code you linked above was just trying to check if value was declared in kwargs at all, and if so, to check its type.  The code was updated in #396 and now reads:

```python
        value = kwargs.pop("value", None)
        if value is not None and value is not UNSET:
```

that may well be all that was needed to fix this here.  I'd say that your line `create_widget(value=None)` is probably never a good idea.  I would leave out `value=` altogether in that case... and perhaps the change in #396 was all that was needed.  let me know if I'm mistaken though!
