### ISSUE TITLE
Functions bound to widgets get called twice on widget creation

### ISSUE THREAD

**Issue by hanjinliu** [napari/magicgui#370]
**Describe the bug**

When I used the `bind` option of `@magicgui` with the latest version, its behavior differs from previous ones.
The function seems to be called twice when a GUI is built.

**To Reproduce**

Run following code.

```python
from magicgui import magicgui
def _get(w=None):
    print(0)
    return 0

@magicgui(a={"bind": _get})
def f(a):
    pass
```

In 0.3.7, two "0" are printed, but in 0.3.4, nothing will be printed.

**Expected behavior**
I think we should avoid calling the function because it may update some global variables or execute some heavy calculations.

**Environment (please complete the following information):**
 - OS: Windows 10
 - backend: PyQt5 5.15.6
 - magicgui version: 0.3.7

**Comment by tlambert03** [comment]
thanks @hanjinliu.  This is fixed upstream in psygnal.  Adding tests in #371, but you can fix locally with `pip install -U psygnal`
