### ISSUE TITLE
GitHub workflows should not use pip install git+https for napari

### ISSUE THREAD

**Issue by jni** [napari/magicgui#377]
The test action uses `pip install git+https://github.com/napari/napari`, which consumes git-lfs bandwidth:

https://github.com/napari/magicgui/blob/159ecdf1f1d7a90955c63cea7fe066e45c15e44f/.github/workflows/test_and_deploy.yml#L80

We should replace it with an explicit checkout of the napari repo (which won't use lfs by default). See napari/napari#4115 for discussion.

**Comment by tlambert03** [comment]
Oh man, this applies to any workflow anywhere huh?

**Comment by jni** [comment]
Yup. @sofroniewn noticed that bandwidth usage was still pretty high. GitHub code search to the rescue!

**Comment by jni** [comment]
Though note that it won't be a problem for *most* end-users, since they won't have lfs installed at all. This is Good News. 😅
