### ISSUE TITLE
Add scrollable window views

### ISSUE THREAD

**Issue by dstansby** [napari/magicgui#380]
I have a large widget with lots of sliders, such that the widget goes off the bottom of my screen. It would be nice if it was possible to resize the window so that it fits on my screen, and have standard window scroll bars to access all the contents of the widget.

**Comment by tlambert03** [comment]
Yep, sounds good.  This is more of a feature request for a scroll area though (not something magicgui yet has).  We _do_ have the ability to resize windows... but the scrollbars don't come for free if you just resize too small (as you've undoubtedly seen).  I'm going to change the title to reflect what would need to be done.  thanks for requesting

**Comment by adamltyson** [comment]
Although https://github.com/napari/magicgui/pull/388 seems to fix it.
