### ISSUE TITLE
Window not showing in when run

### ISSUE THREAD

**Issue by dstansby** [napari/magicgui#387]
**Describe the bug**
When trying to run a really simple example no window is showing. Python is blocked, and an icon appears in the dock, but there is no GUI window associated with the dock icon. As far as I can see this hasn't been reported before. I'm not sure what the brest way is to debug this.

**To Reproduce**
Run the following from a script (ie. `python test.py`):
```python
from magicgui import magicgui, use_app


@magicgui
def add(my_number: int, some_word: str = 'hello', maybe=True):
    pass


if __name__ == '__main__':
    add.show()
    use_app('qt').run()
```

The traceback on interrupting is:
```
  File "<stdin>", line 1, in <module>
  File "/Users/dstansby/projects/napari/magicgui/magicgui/widgets/_bases/widget.py", line 298, in show
    self.__magicgui_app__.run()
  File "/Users/dstansby/projects/napari/magicgui/magicgui/application.py", line 77, in run
    return self._backend._mgui_run()
  File "/Users/dstansby/projects/napari/magicgui/magicgui/backends/_qtpy/application.py", line 24, in _mgui_run
    return app.exec_()
```
**Expected behavior**
A window to appear as shown at https://napari.org/magicgui/index.html#from-types-to-widgets

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 12.3
 - backend: Qt 5.15.4
 - magicgui version: '0.4.0rc2.dev0+g3e3f046.d20220318' (latest main commit as of writing)

**Comment by tlambert03** [comment]
hmm... i'm unable to reproduce my first system.  Will need to dig a bit.  can you tell me a bit more about your system,  Is this an M1 mac? and maybe the full output of conda list or pip list just in case?

**Comment by tlambert03** [comment]
Thanks.  hey @psobolewskiPhD, my possessing friend... 😉 :

if you have a moment, could try out this script on your system and see if you get a window?

```python
from magicgui import magicgui

@magicgui
def add(my_number: int, some_word: str = 'hello', maybe=True):
    pass

add.show(run=True)
```

**Comment by dstansby** [comment]
To check it wasn't an upstream issue I tried a pyqt-only example, and it worked fine for me:

```python
from PyQt5.QtWidgets import *
app = QApplication([])
label = QLabel('Hello World!')
label.show()
app.exec_()
```

**Comment by dstansby** [comment]
Ahhhh this is totally my bad, I was running from inside a `magicgui` checkout with local changes, so it was picking up that copy of `magicgui` instead of the `conda` environments. Running from outside all is fine, sorry for the noise 😞

**Comment by tlambert03** [comment]
ok :joy: ... no worries.  Thanks for the update!  glad to hear you're tinkering with magicgui :)

**Comment by psobolewskiPhD** [comment]
> Thanks. hey @psobolewskiPhD, my M1-possessing friend... 😉 :
> 
> if you have a moment, could try out this script on your system and see if you get a window?
> 
> ```python
> from magicgui import magicgui
> 
> @magicgui
> def add(my_number: int, some_word: str = 'hello', maybe=True):
>     pass
> 
> add.show(run=True)
> ```

🤣 
This runs fine, as I guess expected now?
@dstansby Super glad to not be the only arm64 M1 napari user! 
👊
