### ISSUE TITLE
Contrib module

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#40]
Thinking about the [`try:  from colour import Color`](https://github.com/napari/magicgui/pull/35/files#diff-83980207790782f0abc4b4565da24e66R41) line, and also the [`_magicgui.py` file in napari](https://github.com/napari/napari/blob/master/napari/utils/_magicgui.py) ... neither pattern feels quite right.

I'm thinking both of these belong in some sort of `magicgui.contrib` module... 
- we shouldn't try to import every potentially supported package, but rather search for a specific type annotation through a known list of supported namespaces in the `contrib` module.  For instance, a mapping of namespace to a `register_type`-like function...
- users can still use the `register_type` function for one-off functionality, or third party packages can use it if they don't want to contribute it to magicgui... but a contrib module would collect this functionality and hopefully make it so that neither package needs to be imported until a user has annotated something in a decorated function as a "contrib-supported" type.
- some of these (like color) might be useful enough that we would support them as extras `pip install magicgui[color]`, but they are still imported lazily.

thoughts @GenevieveBuckley?  @jni?  ... suggestions for how that should be implemented in terms of package structure?

**Comment by GenevieveBuckley** [comment]
Those patterns do feel kinda hacky, I think you're right.

I don't know if a `magicgui.contrib` module is the answer, it might be but I can't really envisage what that would be like very clearly. So no, I don't have suggestions in terms of package structure. Are there other projects (python or not) with this type of `contrib` setup?

If it's not too much of a sunk cost, I guess one way to trial it would be to implement a bare bones `magicgui.contrib` for something like color. Maybe then design advantages/flaws might be a little more obvious?

**Comment by GenevieveBuckley** [comment]
One more thing - I think the user demand for this is likely to be very small for magicgui, so it may not be worth the effort. Adding more documentation for `register_types` might be the way to go. Of course, maybe magicgui makes a nice playground to test out this idea for napari itself, without upending napari's code until it's clear the idea works.

**Comment by tlambert03** [comment]
> I can't really envisage what that would be like very clearly

I guess one thing I was imagining is:
```
magicgui
├── contrib
│   ├── __init__.py
│   ├── napari.py
│   └── colour.py
```
where something inside of `napari.py` would say how to map `image.image.Image` to a `register_type` like function.
but...

>  think the user demand for this is likely to be very small for magicgui, so it may not be worth the effort.

I agree 😂  ... but I can't say my coding projects have ever been too terribly driven by user demand 😜

**Comment by jni** [comment]
I don't know, I quite like `register_type` (and I like it better than renaming it `_magictype`, btw!). The only thing that feels hacky to me in that pattern is that it happens on import rather than having to call `napari.register_magicgui_types()` or similar. As you know @tlambert03 I hate import side effects, but in this case I *do* think it should happen when `import napari` is invoked. But perhaps it can be made part of the config.

Which reminds me, I gotta review 1183... 😂

**Comment by tlambert03** [comment]
`register_type` wouldn't be going away.  I guess what I'm after here is this that _neither_ napari nor the end-user should have to explicitly call `napari.register_magicgui_types()` (or similar) whether it be on import, or at any point.  magicgui should be doing that.  In this code block, there is sufficient information for magicgui to know that it needs to figure out whether napari offers a widget for an `Image`, because the user has annotated something in their decorated function with a third-party object:

```python
from magicgui import magicgui
from napari.layers import Image

@magicgui
def func(img: Image) -> Image:
    ...
```

certainly napari needs to tell magicgui how to handle it somehow, but napari shouldn't need to register it "just in case", and the user shouldn't need to call `napari.register_magicgui_types()` (because by annotating with `Image`, they've already indicated they are using that namespace).  But whether magicgui looks in its own `contrib` module, or looks in some standardized place in the third party module doesn't really matter to me... 
An alternative to `contrib` is that third-party packages can use a magicgui `entry_point` that magicgui would take care of importing when necessary

```python
# napari/setup.py (or setup.cfg)

setup(
    entry_points={
        "magicgui_types": ["napari = napari.utils._magicgui",]
    }
)
```

**Comment by tlambert03** [comment]
> But whether magicgui looks in its own contrib module, or looks in some standardized place in the third party module doesn't really matter to me...

the rationale for `contrib`, over (or in addition to) the `entry_point`  is that I don't really want to have to push PRs to third party packages like `colour` to support magicgui in their `setup.py` ... but I also don't want to "try import" everything that we have bundled support for (like, potentially, `colour`).  So we need some modular internal place to put widgets that work with non-standard-lib Types
