### ISSUE TITLE
Make pre-releases of magicgui

### ISSUE THREAD

**Issue by Czaki** [napari/magicgui#421]
It happens from time to time that a new release of magicgui breaks existing packages (0.5.0 breaks the PartSeg test by preventing the removal layer and keeping teardown forever). But as it is the preferred way to create napari plugins maybe it is worth making pre-releases of magicgui to fast catch problems.

**Comment by tlambert03** [comment]
Sure can do,

can you elaborate on “0.5.0 breaks the PartSeg test by preventing the removal layer and keeping teardown forever”

and do you have a pre test on a cron job that would have caught this?

**Comment by Czaki** [comment]
> and do you have a pre test on a cron job that would have caught this?

yes, https://github.com/4DNucleome/PartSeg/blob/develop/.github/workflows/test_prereleases.yml

> can you elaborate on “0.5.0 breaks the PartSeg test by preventing the removal layer and keeping teardown forever”

Currently checking but it looks like adding a layer call `reset_choices` on widgets (as expected) but this causes call `reset_choices` on Combobox for Enum (`create_widget(annotation=SearchType, label="Search type")` where `SearchType` is Enum). that reset voices in this enum and emit the signal that value is changed (even if the value is same as before reset).

**Comment by Czaki** [comment]
I'm working on PR with bugfix. 

> Ok, sorry about that. Reset choices is generally a mess :/

Yes. It is hard to understand.

**Comment by tlambert03** [comment]
For what it's worth, I'm probably going to change that behavior soon. Such that reset choices never gets called automatically (eg on Reparenting).  It would be up to napari to add that event connection.  More explicit, should lead to less surprising behavior
