### ISSUE TITLE
Docs for 0.5.1 not updated

### ISSUE THREAD

**Issue by dstansby** [napari/magicgui#426]
I'm looking for the documentation for the new `scrollable` feature (https://github.com/napari/magicgui/pull/388), that I think was released in `0.5`, but https://napari.org/magicgui/api/magicgui.html seems to not have this documentation - I presume because it's out of date and something's gone wrong with automatically updating and pushin the docs?

**Comment by tlambert03** [comment]
Yep looks like it https://github.com/napari/magicgui/actions/runs/2495448723
