### ISSUE TITLE
RadioButtons with multiple choices

### ISSUE THREAD

**Issue by CedricEsp** [napari/magicgui#430]
Hello,
I am trying to use the `RadioButtons` as an option to select multiple options instead of `Select` but I can't get it to work and wonder if I am doing something wrong?
Here is a minimal version of what I am doing:
```
choices = ["A", "B", "C", "D", "E"]
w3 = widgets.RadioButtons(choices=choices, label='Channels:',value=["A", "B"], 
                         orientation='horizontal', allow_multiple=True)
w3.show()
w3.value
```
Thank you for your help.

**Comment by tlambert03** [comment]
RadioButtons are mutually exclusive (see [docs](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.RadioButtons.html?highlight=radiobuttons))

**Comment by CedricEsp** [comment]
Thank you!
