### ISSUE TITLE
Enable Return press on "keyboardable" widgets to call the wrapped function

### ISSUE THREAD

**Issue by gselzer** [napari/magicgui#434]
While reviewing imagej/napari-imagej#70, @ctrueden was hoping that pressing Return while focusing on a keyboardable component of a magicgui widget would call the function with the current inputs. Specifically, he noted:
> Pressing enter while one of the widget's components is focused, or while the Run button is focused, does not execute the module.

This is a problem that is seemingly better solved here.

For example, suppose I wrote the following widget:
```python3
@magic_factory()
def example_magic_widget(b: int) -> List["napari.types.LayerDataTuple"]:
    return [(np.ones((4, 4)), {'name': f"foo{i}"}) for i in range(b)]
```
This generates the following widget in napari:
![image](https://user-images.githubusercontent.com/29754838/176700344-b2e350ed-5390-478a-8487-04bafb041179.png)
It might be nice that, while focused on/editing the `b` parameter, pressing Return would call the wrapped function.

Do you have more to add @ctrueden?

**Comment by ctrueden** [comment]
Nope, I think that about sums it up. Thanks @gselzer!
