### ISSUE TITLE
Widget label editable 

### ISSUE THREAD

**Issue by sfcaracciolo** [napari/magicgui#45]
I create this feature request like @tlambert03 have suggested here https://forum.image.sc/t/magicgui-and-docked-widget-questions/44983 

It would be fine, add a "display_name" parameter on the @magicgui decorator to personalize the string showed left to the widget.

For instance, this fragment:

```python
import napari
from magicgui import magicgui

@magicgui()
def test_gui(var_name: int = 0):
    pass

with napari.gui_qt():
    widget = test_gui.Gui(show=True)
```

it has this output, where "var_name" label is not editable

![Screenshot_2020-11-11_19-10-21](https://user-images.githubusercontent.com/41028670/98870103-91ae4400-2451-11eb-9ddd-90c7c89d420a.png)

@jni suggested using a "display_name" option on the @magicgui decorator like this:

```python
@magicgui(var_name={"display_name": "some editable string"})
def test_gui(var_name: int = 0):
    pass
```

Cheers!

**Comment by tlambert03** [comment]
implemented in #48, and carried over into the new API coming in v0.2.0
