### ISSUE TITLE
Verbose fail on lack of matching widget for provided type

### ISSUE THREAD

**Issue by Czaki** [napari/magicgui#473]
When working with magicgui one of the problems is that it silently defaults to `widgets.EmptyWidget` for an unknown type. So it means that there is no clear way to verify if created widget contains all required fields without manually type-checking of each field. Writing such a test is really time-consuming. 

It will be nice to have one of these options:

1. change behavior to raise an exception (for example, ValueError) instead of return EmptyWidget:
   https://github.com/napari/magicgui/blob/9e29739b4047dd2fb7b223152513170aad4a1ebc/magicgui/type_map.py#L211
2. allow control of this behavior from code. This allows to at least tests to get an exception instead of a silent fail of matching types. 
3. same as above but with the default behavior change to raise an exception. 

I could implement it, but I would ask you which option you prefer @tlambert03.

**Comment by tlambert03** [comment]
The current empty widget behavior was implemented on request: https://github.com/napari/magicgui/pull/103

so we can't directly implement option number one without at least an opt-in flag (option number 2?)... but I would fully be in favor of an option that raises an exception if a widget cannot be found
