### ISSUE TITLE
Restrict dependencies to compatible versions

### ISSUE THREAD

**Issue by aeisenbarth** [napari/magicgui#488]
Older versions of magicgui cannot be installed anymore because they pull in the latest versions of dependencies which may be incompatible.

## Example

If you install magicgui==0.3.7, it depends on psygnal>=0.3.0, which is also satisfied by psygnal==0.6.0. But that version gives an import error:
```
AttributeError: module 'psygnal._signal' has no attribute 'NormedCallback'
```

Instead, one could consider restricting dependencies to compatible versions, e.g. if magicgui==0.3.7 depended on psygnal~=0.3.0, and in a later release, magicgui==0.6.0 would depend on psygnal~=0.6.0.

**Comment by tlambert03** [comment]
I'm sorry @aeisenbarth, but pinning a lower level dependency like that has equally bad unexpected consequences.  For example:
- package A uses pymmcore-plus, which needs newer psygnal versions
- package B installs magicgui==0.3.7, causing pip to downgrade psygnal and break package A

It's tempting to feel like strong pinning and adherence to semantic versioning will save us all here, but after a lot of contemplation and reading about this, I feel like it's not the right answer.  If you're curious, I'd recommend:

- [Semantic Versioning Will Not Save You](https://hynek.me/articles/semver-will-not-save-you/) - *Hynek Schlawack*
- [Version numbers: how to use them?](https://bernat.tech/posts/version-numbers/) - *Bernát Gábor*
- [Why I don't like SemVer anymore](https://snarky.ca/why-i-dont-like-semver/) - *Brett Cannon*
- [Should You Use Upper Bound Version Constraints?](https://iscinumpy.dev/post/bound-version-constraints/) - *Henry Schreiner*
- [Versioning Software](https://caremad.io/posts/2016/02/versioning-software/) - *Donald Stufft*


So, I'm definitely sorry that magicgui0.3.7 doesn't work with the newest version of psygnal.  And, in the conda world, we actually _can_ go back and apply such a patch.  But in pip, the state of the art still just doesn't provide a solution that I am comfortable enough to implement hard pins in magicgui on something like psygnal, used by other packages
