### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by jesusdpa1** [napari/magicgui#6]
When trying to run the sample code for image arithmetic the script is giving the following error 

return choices(self, self._arg_types[name])
TypeError: get_layers() takes 1 positional argument but 2 were given

**Comment by tlambert03** [comment]
Thanks @jesusdpa1, I was hoping to see a full traceback... I suspect you might be running old examples (and the traceback might reveal that).  Can you check whether your example code matches the current master examples?
https://github.com/napari/magicgui/blob/master/examples/napari_image_arithmetic.py

**Comment by jesusdpa1** [comment]
Good catch, and sorry, this time I am posting the complete traceback:

The code that I was using was the one available in the website. I ran now the new example and got the following error

Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/magicgui/core.py", line 315, in set_widget
    WidgetType = type2widget(arg_type)
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/magicgui/core.py", line 775, in type2widget
    raise TypeError(f'Unable to retrieve widget type for argument type "{type_}".')
TypeError: Unable to retrieve widget type for argument type "<class 'napari.layers.image.image.Image'>".
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d10e5cf75035>", line 41, in <module>
    gui = image_arithmetic.Gui()
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/magicgui/core.py", line 607, in __init__
    **param_options,
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/magicgui/core.py", line 183, in __init__
    dtype=(None if param.annotation is param.empty else param.annotation),
  File "/home/jesusdpa/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/magicgui/core.py", line 324, in set_widget
    raise TypeError(msg)
TypeError: Unable to find the appropriate widget for function "image_arithmetic", arg "layerA", type "<class 'napari.layers.image.image.Image'>".

Thank you again for your help!

**Comment by tlambert03** [comment]
ok thanks, there's a couple things going on here:

1. some stuff changed with `register_type` in https://github.com/napari/magicgui/commit/fa3f748ea2612c5ee2efc81a9a3acd00a66f466a that hasn't made it to the examples in the docs yet.
2. we added support for `magicgui` to `napari` 4 days ago in https://github.com/napari/napari/pull/981, which actually greatly simplifies the example in the docs (you no longer need to use `register_type`), but that hasn't made it to the release yet.

I will fix the docs soon, and a new napari release will probably come in the next few weeks.  but if you want to try the arithmetic example right now you can do one of two things:

1. use the pip installable `magicgui` and `napari` and use [`register_type`](https://magicgui.readthedocs.io/en/latest/type_inference/#register_type) on your own

<details>
<summary>Full code example</summary>

```python
from enum import Enum
from typing import Any, Tuple, Type

import numpy

from magicgui import magicgui, register_type
from napari import Viewer, gui_qt, layers

# the section between the # symbols will not be required
# after the next napari release
#################################

def get_layers(gui, layer_type: Type[layers.Layer]) -> Tuple[layers.Layer, ...]:
    try:
        viewer = gui.parent().qt_viewer.viewer
        return tuple(l for l in viewer.layers if isinstance(l, layer_type))
    except AttributeError:
        return ()


def show_layer_result(gui, result: Any, return_type: Type[layers.Layer]) -> None:
    if result is None:
        return

    try:
        viewer = gui.parent().qt_viewer.viewer
    except AttributeError:
        return

    try:
        viewer.layers[gui.result_name].data = result
    except KeyError:
        adder = getattr(viewer, f"add_{return_type.__name__.lower()}")
        adder(data=result, name=gui.result_name)

register_type(layers.Layer, choices=get_layers, return_callback=show_layer_result)

############################

class Operation(Enum):
    add = numpy.add
    subtract = numpy.subtract
    multiply = numpy.multiply
    divide = numpy.divide


with gui_qt():
    # create a viewer and add a couple image layers
    viewer = Viewer()
    viewer.add_shapes(20 * numpy.random.random((5, 4, 2)), name="Shapes")
    viewer.add_image(numpy.random.rand(20, 20), name=f"Layer 1")
    viewer.add_image(numpy.random.rand(20, 20), name=f"Layer 2")

    @magicgui(call_button="execute")
    def image_arithmetic(
        layerA: layers.Image, operation: Operation, layerB: layers.Image
    ) -> layers.Image:
        """Add, subtracts, multiplies, or divides to image layers with equal shape."""
        return operation.value(layerA.data, layerB.data)

    # instantiate the widget
    gui = image_arithmetic.Gui()
    # parentChanged is a special signal set on MagicGui classes in the Qt backend
    # we use it here to update the layer choices when the widget is docked in a viewer.
    gui.parentChanged.connect(gui.refresh_choices)

    # add our new magicgui widget to the viewer
    viewer.window.add_dock_widget(gui)

    # notice how the dropdowns only show the current image layers... not the shapes.
    # that is because of how we used `register_type` above.

    # keep the dropdown menus in the gui in sync with the layer model
    viewer.layers.events.added.connect(lambda x: gui.refresh_choices())
    viewer.layers.events.removed.connect(lambda x: gui.refresh_choices())
```

</details>

2. pip install the unreleased master branch of napari and run the example without using the `register_type` function at all (i.e. remove the section of code between then `#` signs)

```sh
pip install git+git://github.com/napari/napari.git
```

**Comment by jesusdpa1** [comment]
Thank you Talley, I'll start testing and keep you posted
