### ISSUE TITLE
Need consensus on "layout" vs "orientation"

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#63]
Howdie @jni, @sofroniewn, @haesleinhuepf

Just released 0.2.0, but then realized I still need to resolve the "layout" vs "orientation" wording from #54.

I need some input!  "`orientation`" makes sense for an "HBox" or "VBox"-like layout, but I would like to eventually add support for a `grid` layout ... So "layout" seems more flexible.  I like it slightly less for non-gridded containers, but would like to avoid having both orientation and layout words floating around.  I need someone to tell me what to do :)

**Comment by sofroniewn** [comment]
I'd go with the more general `layout`. I'm fine with `layout='vertical'` and the extra flexibility could come in handy one day. Maybe it takes a dict with more option etc. or `layout='form'`. Who knows
