### ISSUE TITLE
Should we permanently resolve ForwardRef type annotations?

### ISSUE THREAD

**Issue by tlambert03** [napari/magicgui#65]
In https://github.com/napari/napari/pull/1856#discussion_r549041360, @sofroniewn shows an issue in which napari's callback function fails when a ForwardRef is used as a type annotation.  While #52 takes care of this internally... currently, it's up to all dependent libraries to do it for themselves.  It would probably be easy enough to make sure that `widget.annotation` is always a resolved ForwardRef?

**Comment by sofroniewn** [comment]
Yeah I think we should, it just makes it easier for people upstream not to worry about this
