### ISSUE TITLE
napari examples in the docs are broken

### ISSUE THREAD

**Issue by alisterburt** [napari/magicgui#72]
I just tried to go through the example napari integrations and it seems like they're currently broken - I guess this is a result of the 0.2.0 update

The decorated functions are returned as `FunctionGui` objects which can't be added with the `Viewer.add_dock_widget()` method, adding the `native` property of the `FunctionGui` instead added the widget to the viewer but it wasn't aware of the napari side of things.

What is the best way to integrate with the napari viewer at the moment? I didn't find an obvious replacement method in the window of the viewer. Once I know I'd be happy to update the docs accordingly

Hope you're enjoying the holidays!

**Comment by tlambert03** [comment]
> What is the best way to integrate with the napari viewer at the moment?

you'll need the current napari master with https://github.com/napari/napari/pull/1994
you can probably do `pip install git+https://github.com/napari/napari.git`

we're working on releasing this update very soon!

**Comment by alisterburt** [comment]
aaah perfect, should've looked at the merged PRs! awesome, I'll download the master to play with it

**Comment by tlambert03** [comment]
no worries... it's the difficult dance of updating two inter-dependent repos at the same time! 😝

**Comment by alisterburt** [comment]
```python
@magicgui(
    auto_call=True,
    sigma={"widget_type": "FloatSlider", "max": 6},
    mode={"choices": ["reflect", "constant", "nearest", "mirror", "wrap"]},
)
def gaussian_blur(layer: Image, sigma: float = 1.0, mode="nearest") -> Image:
    """Apply a gaussian blur to ``layer``."""
    if layer:
        return skimage.filters.gaussian(layer.data, sigma=sigma, mode=mode)
```

for info, the above example is giving a `ValueError` 
```ValueError: Could not pick widget for type: <class 'napari.layers.image.image.Image'>```

This was from the napari master and magicgui 0.2.0

**Comment by tlambert03** [comment]
I'm afraid I can't repeat it...
```
conda create -y -n test python=3.8
conda activate test
pip install magicgui git+https://github.com/napari/napari.git pyqt5 scikit-image
curl https://raw.githubusercontent.com/napari/magicgui/master/examples/napari_param_sweep.py -o napari_param_sweep.py
python napari_param_sweep.py
```

**Comment by alisterburt** [comment]
weird, not sure what I was doing wrong but that works for me too! thanks

**Comment by tlambert03** [comment]
if you still have the broken environment, maybe run `napari --info` and `conda list`?

**Comment by alisterburt** [comment]
already nuked it unfortunately, didn't know about napari --info though! was always checking __version__

**Comment by tlambert03** [comment]
> already nuked it unfortunately

that's the spirit! onward and upward :joy:

i'll leave this open until you're confident it's working... but close at your discretion.  Ultimately, the fix is on the napari side

**Comment by alisterburt** [comment]
all works as expected! oooh these buttons are fun
